#!/usr/bin/sh

### Usage ###
# In project root directory run:
# cp git-hooks/pre-commit .git/hooks


PY_FILES=$(git diff --cached --name-only -- '***.py')

# Need to skip if no changed files cause flake8 checks everything in that case
if [ -z "$PY_FILES" ];
then
    exit 0
fi

echo "🚨 Running pre-commit hook for black and flake8"

EXIT_STATUS=0

echo "➡  Running black"
pipenv run black --check --diff $PY_FILES || EXIT_STATUS=$?
echo "➡  Running flake8"
pipenv run flake8 $PY_FILES || EXIT_STATUS=$?

exit $EXIT_STATUS
