#!/usr/bin/bash

### Usage ###
# In project root directory run:
# cp git-hooks/pre-commit .git/hooks


echo "🚨 Running pre-commit hook for black and flake8"

# Activate virtual environment
VENV_LOCATION=$(pipenv --venv)
source $VENV_LOCATION/bin/activate

EXIT_STATUS=0

while read path;
do

    entry=$(git ls-files --stage -- "$path")
    hash=$(echo $entry | grep -Po "(?<=[0-9]{6} )[a-f0-9]{40}" -)
    content=$(git cat-file -p $hash)

    echo ""
    echo 📄 $path

    echo "➡  Running black"
    echo "$content" | black --quiet --check --diff --stdin-filename "$path" - || EXIT_STATUS=$?

    echo "➡  Running flake8"
    echo "$content" | flake8 --stdin-display-name "$path" - || EXIT_STATUS=$?

done < <(git diff --cached --name-only --diff-filter=d -- '***.py')

exit $EXIT_STATUS
