# Generated by Django 3.0.7 on 2020-06-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quintly_profile_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Instagram-Account',
                'verbose_name_plural': 'Instagram-Accounts',
            },
        ),
        migrations.CreateModel(
            name='InstaStories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Text')),
                ('time', models.DateField(verbose_name='Datum')),
                ('story_type', models.CharField(max_length=200, verbose_name='Typ')),
                ('comments', models.IntegerField(verbose_name='Kommentare')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('reach', models.IntegerField(verbose_name='Reichweite')),
                ('impressions', models.IntegerField(verbose_name='Impressions')),
                ('insta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', related_query_name='story', to='okr.Insta')),
            ],
        ),
        migrations.CreateModel(
            name='InstaPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Text')),
                ('time', models.DateField(verbose_name='Datum')),
                ('post_type', models.CharField(max_length=20, verbose_name='Typ')),
                ('comments', models.IntegerField(verbose_name='Kommentare')),
                ('likes', models.IntegerField(verbose_name='Likes')),
                ('reach', models.IntegerField(verbose_name='Reichweite')),
                ('impressions', models.IntegerField(verbose_name='Impressions')),
                ('link', models.URLField(verbose_name='Link')),
                ('insta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', related_query_name='post', to='okr.Insta')),
            ],
        ),
        migrations.CreateModel(
            name='InstaInsights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='Datum')),
                ('interval', models.CharField(choices=[('daily', 'Täglich'), ('weekly', 'Wöchentlich'), ('monthly', 'Monatlich')], max_length=10, verbose_name='Zeitraum')),
                ('reach', models.IntegerField(verbose_name='Reichweite')),
                ('impressions', models.IntegerField(verbose_name='Impressions')),
                ('followers', models.IntegerField(verbose_name='Follower')),
                ('followers_change', models.IntegerField(verbose_name='Veränderung Follower')),
                ('posts_change', models.IntegerField(verbose_name='Veränderung Posts')),
                ('textMessageClicksDay', models.IntegerField(null=True, verbose_name='Nachricht senden')),
                ('emailContactsDay', models.IntegerField(null=True, verbose_name='Email senden')),
                ('insta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', related_query_name='insight', to='okr.Insta')),
            ],
        ),
        migrations.CreateModel(
            name='Collaborations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(verbose_name='Datum')),
                ('influencer', models.CharField(max_length=100, verbose_name='Influencer:in')),
                ('followers', models.IntegerField(verbose_name='Follower')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('insta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', related_query_name='collaboration', to='okr.Insta')),
            ],
        ),
    ]
