# Generated by Django 3.0.7 on 2020-06-25 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTube",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("quintly_profile_id", models.IntegerField()),
            ],
            options={
                "verbose_name": "YouTube-Account",
                "verbose_name_plural": "YouTube-Accounts",
            },
        ),
        migrations.CreateModel(
            name="YouTubeAnalytics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField(verbose_name="Datum")),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Täglich"),
                            ("weekly", "Wöchentlich"),
                            ("monthly", "Monatlich"),
                        ],
                        max_length=10,
                        verbose_name="Zeitraum",
                    ),
                ),
                ("views", models.IntegerField(null=True, verbose_name="Views")),
                ("likes", models.IntegerField(null=True, verbose_name="Likes")),
                ("dislikes", models.IntegerField(null=True, verbose_name="Dislikes")),
                (
                    "estimated_minutes_watched",
                    models.IntegerField(
                        null=True, verbose_name="Gesehene Minuten (geschätzt)"
                    ),
                ),
                (
                    "average_view_duration",
                    models.IntegerField(null=True, verbose_name="Sehdauer im Schnitt"),
                ),
                (
                    "youtube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytic",
                        related_query_name="analytics",
                        to="okr.YouTube",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube-Analytic",
                "verbose_name_plural": "YouTube-Analytics",
                "unique_together": {("youtube", "time", "interval")},
            },
        ),
    ]
