# Generated by Django 3.0.7 on 2020-06-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instapost",
            name="external_id",
            field=models.CharField(
                default="", max_length=25, unique=True, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="instastory",
            name="external_id",
            field=models.CharField(
                default="", max_length=25, unique=True, verbose_name="ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instapost",
            name="time",
            field=models.DateTimeField(verbose_name="Erstellt"),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="time",
            field=models.DateTimeField(verbose_name="Erstellt"),
        ),
        migrations.AlterUniqueTogether(
            name="instainsight", unique_together={("insta", "time", "interval")},
        ),
    ]
