# Generated by Django 3.0.7 on 2020-06-25 15:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0003_youtubetrafficsource"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubetrafficsource",
            name="impressions_home",
            field=models.IntegerField(default=0, verbose_name="Impressions (Home)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubetrafficsource",
            name="impressions_subscriptions",
            field=models.IntegerField(default=0, verbose_name="Impressions (Abos)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubetrafficsource",
            name="impressions_trending",
            field=models.IntegerField(default=0, verbose_name="Impressions (Trending)"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubetrafficsource",
            name="last_updated",
            field=models.DateTimeField(auto_now=True, verbose_name="Zuletzt upgedated"),
        ),
        migrations.AddField(
            model_name="youtubetrafficsource",
            name="time",
            field=models.DateField(
                default=datetime.date(2020, 6, 25), verbose_name="Datum"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="youtubetrafficsource",
            name="youtube",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traffic_source",
                related_query_name="traffic_sources",
                to="okr.YouTube",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="youtubetrafficsource",
            unique_together={("youtube", "time")},
        ),
    ]
