# Generated by Django 3.0.7 on 2020-06-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0004_auto_20200624_1201"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instainsight",
            name="impressions",
            field=models.IntegerField(null=True, verbose_name="Impressions"),
        ),
        migrations.AlterField(
            model_name="instainsight",
            name="reach",
            field=models.IntegerField(null=True, verbose_name="Reichweite"),
        ),
    ]
