# Generated by Django 3.0.7 on 2020-06-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0005_auto_20200625_1724"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instacollaboration",
            name="description",
            field=models.TextField(verbose_name="Thema"),
        ),
        migrations.AlterField(
            model_name="instacollaboration",
            name="followers",
            field=models.IntegerField(
                help_text="Anzahl der Follower der Influencer*in",
                verbose_name="Follower",
            ),
        ),
        migrations.AlterField(
            model_name="instacollaboration",
            name="influencer",
            field=models.CharField(
                max_length=100, verbose_name="Influencer*in (Account-Name)"
            ),
        ),
    ]
