# Generated by Django 3.0.7 on 2020-06-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0005_auto_20200624_1508"),
    ]

    operations = [
        migrations.AddField(
            model_name="instastory",
            name="link",
            field=models.URLField(default="", max_length=1024, verbose_name="Link"),
            preserve_default=False,
        ),
    ]
