# Generated by Django 3.0.7 on 2020-06-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0007_auto_20200624_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instastory',
            name='caption',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
    ]
