# Generated by Django 3.0.7 on 2020-06-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0008_auto_20200626_1134"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeAgeRangeDuration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age_13_17", models.DurationField(verbose_name="13 - 17")),
                ("age_18_24", models.DurationField(verbose_name="18 - 24")),
                ("age_25_34", models.DurationField(verbose_name="25 - 34")),
                ("age_35_44", models.DurationField(verbose_name="35 - 44")),
                ("age_45_54", models.DurationField(verbose_name="45 - 54")),
                ("age_55_64", models.DurationField(verbose_name="55 - 64")),
                ("age_65_plus", models.DurationField(verbose_name="65+")),
            ],
            options={
                "verbose_name": "YouTube Age-Range (Viewtime)",
                "verbose_name_plural": "YouTube Age-Ranges (Viewtime)",
            },
        ),
        migrations.CreateModel(
            name="YouTubeAgeRangePercentage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "age_13_17",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="13 - 17"
                    ),
                ),
                (
                    "age_18_24",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="18 - 24"
                    ),
                ),
                (
                    "age_25_34",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="25 - 34"
                    ),
                ),
                (
                    "age_35_44",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="35 - 44"
                    ),
                ),
                (
                    "age_45_54",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="45 - 54"
                    ),
                ),
                (
                    "age_55_64",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="55 - 64"
                    ),
                ),
                (
                    "age_65_plus",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="65+"
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Age-Range (Prozent)",
                "verbose_name_plural": "YouTube Age-Ranges (Prozent)",
            },
        ),
        migrations.CreateModel(
            name="YouTubeViewerAge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField(verbose_name="Datum")),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Täglich"),
                            ("weekly", "Wöchentlich"),
                            ("monthly", "Monatlich"),
                        ],
                        max_length=10,
                        verbose_name="Zeitraum",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "average_percentage_viewed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="okr.YouTubeAgeRangePercentage",
                        verbose_name="Durchschnittliche View-Time (% des Videos)",
                    ),
                ),
                (
                    "average_view_duration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="okr.YouTubeAgeRangeDuration",
                        verbose_name="Durchschnittliche View-Time (absolut)",
                    ),
                ),
                (
                    "views",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="okr.YouTubeAgeRangePercentage",
                        verbose_name="Views (%)",
                    ),
                ),
                (
                    "watch_time",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        related_query_name="+",
                        to="okr.YouTubeAgeRangePercentage",
                        verbose_name="Watch-Time (%)",
                    ),
                ),
                (
                    "youtube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="age_range",
                        related_query_name="age_ranges",
                        to="okr.YouTube",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Viewer-Age",
                "verbose_name_plural": "YouTube Viewer-Ages",
                "unique_together": {("youtube", "time", "interval")},
            },
        ),
    ]
