# Generated by Django 3.0.7 on 2020-06-26 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "okr",
            "0009_youtubeagerangeduration_youtubeagerangepercentage_youtubeviewerage",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubeanalytics",
            options={
                "verbose_name": "YouTube-Analytics",
                "verbose_name_plural": "YouTube-Analytics",
            },
        ),
        migrations.AlterField(
            model_name="instacollaboration",
            name="insta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collaborations",
                related_query_name="collaboration",
                to="okr.Insta",
                verbose_name="Instagram-Account",
            ),
        ),
        migrations.AlterField(
            model_name="instainsight",
            name="insta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                related_query_name="insight",
                to="okr.Insta",
                verbose_name="Instagram-Account",
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="insta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                related_query_name="post",
                to="okr.Insta",
                verbose_name="Instagram-Account",
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="insta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                related_query_name="story",
                to="okr.Insta",
                verbose_name="Instagram-Account",
            ),
        ),
        migrations.AlterField(
            model_name="youtubeanalytics",
            name="youtube",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytic",
                related_query_name="analytics",
                to="okr.YouTube",
                verbose_name="YouTube-Account",
            ),
        ),
        migrations.AlterField(
            model_name="youtubetrafficsource",
            name="youtube",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traffic_source",
                related_query_name="traffic_sources",
                to="okr.YouTube",
                verbose_name="YouTube-Account",
            ),
        ),
        migrations.AlterField(
            model_name="youtubeviewerage",
            name="youtube",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="age_range",
                related_query_name="age_ranges",
                to="okr.YouTube",
                verbose_name="YouTube-Account",
            ),
        ),
    ]
