# Generated by Django 3.0.7 on 2020-07-21 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0010_auto_20200626_1638"),
    ]

    operations = [
        migrations.CreateModel(
            name="Podcast",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("feed_url", models.URLField(max_length=1024, verbose_name="Feed-URL")),
                ("author", models.CharField(max_length=200, verbose_name="Autor")),
                ("image", models.URLField(max_length=1024, verbose_name="Bild")),
                ("description", models.TextField(verbose_name="Beschreibung")),
            ],
            options={
                "verbose_name": "Podcast",
                "verbose_name_plural": "Podcasts",
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=400, verbose_name="Titel")),
                ("description", models.TextField(verbose_name="Beschreibung")),
                (
                    "publication_date_time",
                    models.DateTimeField(verbose_name="Veröffentlicht am"),
                ),
                ("media", models.URLField(max_length=1024, verbose_name="Media-URL")),
                ("zmdb_id", models.IntegerField(unique=True, verbose_name="ZMDB-ID")),
                ("duratation", models.DurationField(verbose_name="Audio-Länge")),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        related_query_name="episode",
                        to="okr.Podcast",
                        verbose_name="Podcast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Episode",
                "verbose_name_plural": "Podcast-Episoden",
            },
        ),
        migrations.CreateModel(
            name="PodcastDataSpotifyFollowers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("followers", models.IntegerField(verbose_name="Follower")),
                (
                    "podcast",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        related_query_name="followers",
                        to="okr.Podcast",
                        verbose_name="Podcast",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Spotify-Follower",
                "verbose_name_plural": "Podcast-Spotify-Follower",
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisodeDataSpotifyUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("age_0_17", models.IntegerField(verbose_name="0-17 Jahre")),
                ("age_18_22", models.IntegerField(verbose_name="18-22 Jahre")),
                ("age_23_27", models.IntegerField(verbose_name="23-27 Jahre")),
                ("age_28_34", models.IntegerField(verbose_name="28-34 Jahre")),
                ("age_35_44", models.IntegerField(verbose_name="35-44 Jahre")),
                ("age_45_59", models.IntegerField(verbose_name="45-59 Jahre")),
                ("age_60_150", models.IntegerField(verbose_name="60-150 Jahre")),
                ("age_unknown", models.IntegerField(verbose_name="Unbekanntes Alter")),
                ("gender_female", models.IntegerField(verbose_name="Weiblich")),
                ("gender_male", models.IntegerField(verbose_name="Männlich")),
                ("gender_non_binary", models.IntegerField(verbose_name="Non_binary")),
                (
                    "gender_not_specified",
                    models.IntegerField(verbose_name="Geschlecht nicht angegeben"),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_spotify_user",
                        related_query_name="data_spotify_user",
                        to="okr.PodcastEpisode",
                        verbose_name="Episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Episoden-Nutzer (Spotify)",
                "verbose_name_plural": "Podcast-Episoden-Nutzer (Spotify)",
                "unique_together": {("date", "episode")},
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisodeDataSpotifyPerformance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("average_listen", models.TimeField(verbose_name="Hörzeit im Schnitt")),
                ("quartile_1", models.IntegerField(verbose_name="1. Quartil")),
                ("quartile_2", models.IntegerField(verbose_name="2. Quartil")),
                ("quartile_3", models.IntegerField(verbose_name="3. Quartil")),
                ("complete", models.IntegerField(verbose_name="Komplett")),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_spotify_performance",
                        related_query_name="data_spotify_performance",
                        to="okr.PodcastEpisode",
                        verbose_name="Episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Episoden-Performance (Spotify)",
                "verbose_name_plural": "Podcast-Episoden-Performance (Spotify)",
                "unique_together": {("date", "episode")},
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisodeDataSpotify",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("starts", models.IntegerField(verbose_name="Starts")),
                ("streams", models.IntegerField(verbose_name="Streams")),
                ("listeners", models.IntegerField(verbose_name="Hörer")),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_spotify",
                        related_query_name="data_spotify",
                        to="okr.PodcastEpisode",
                        verbose_name="Episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Episoden-Abruf (Spotify)",
                "verbose_name_plural": "Podcast-Episoden-Abrufe (Spotify)",
                "unique_together": {("date", "episode")},
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisodeDataPodstatOndemand",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("nv", models.IntegerField(verbose_name="Nutzungsvorgang")),
                (
                    "nv10",
                    models.IntegerField(verbose_name="Nutzungsvorgang über 10 Sec."),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_podstat_ondemand",
                        related_query_name="data_podstat_ondemand",
                        to="okr.PodcastEpisode",
                        verbose_name="Episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Episoden-Streams (Podstat)",
                "verbose_name_plural": "Podcast-Episoden-Streams (Podstat)",
                "unique_together": {("date", "episode")},
            },
        ),
        migrations.CreateModel(
            name="PodcastEpisodeDataPodstatDownload",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("nv", models.IntegerField(verbose_name="Nutzungsvorgang")),
                (
                    "nv10",
                    models.IntegerField(verbose_name="Nutzungsvorgang über 10 Sec."),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_podstat_download",
                        related_query_name="data_podstat_download",
                        to="okr.PodcastEpisode",
                        verbose_name="Episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Episoden-Downloads (Podstat)",
                "verbose_name_plural": "Podcast-Episoden-Downloads (Podstat)",
                "unique_together": {("date", "episode")},
            },
        ),
    ]
