# Generated by Django 3.0.8 on 2020-07-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0012_auto_20200721_1704"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instacollaboration", old_name="time", new_name="date",
        ),
        migrations.RenameField(
            model_name="instainsight", old_name="time", new_name="date",
        ),
        migrations.RenameField(
            model_name="instapost", old_name="time", new_name="created_at",
        ),
        migrations.RenameField(
            model_name="instastory", old_name="time", new_name="created_at",
        ),
        migrations.RenameField(
            model_name="youtubeanalytics", old_name="time", new_name="date",
        ),
        migrations.RenameField(
            model_name="youtubetrafficsource", old_name="time", new_name="date",
        ),
        migrations.RenameField(
            model_name="youtubeviewerage", old_name="time", new_name="date",
        ),
        migrations.AlterUniqueTogether(
            name="instainsight", unique_together={("insta", "date", "interval")},
        ),
        migrations.AlterUniqueTogether(
            name="youtubeanalytics", unique_together={("youtube", "date", "interval")},
        ),
        migrations.AlterUniqueTogether(
            name="youtubetrafficsource", unique_together={("youtube", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="youtubeviewerage", unique_together={("youtube", "date", "interval")},
        ),
    ]
