# Generated by Django 3.1.2 on 2020-10-20 15:44

from django.db import migrations, models
import django.db.models.deletion


def migrate_podstat(apps, schema_editor):
    # Old models - Everything relates to NV
    PodcastEpisodeDataPodstatDownload = apps.get_model(
        "okr", "PodcastEpisodeDataPodstatDownload"
    )
    PodcastEpisodeDataPodstatOndemand = apps.get_model(
        "okr", "PodcastEpisodeDataPodstatOndemand"
    )

    # New model - Everything relates to Podstat
    PodcastEpisodeDataPodstat = apps.get_model("okr", "PodcastEpisodeDataPodstat")

    for entry in PodcastEpisodeDataPodstatDownload.objects.all():
        obj = PodcastEpisodeDataPodstat(
            episode=entry.episode,
            date=entry.date,
            downloads=entry.nv,
            ondemand=0,
            last_updated=entry.last_updated,
        )
        obj.save()

    for entry in PodcastEpisodeDataPodstatOndemand.objects.all():
        try:
            obj = PodcastEpisodeDataPodstat.objects.get(
                episode=entry.episode,
                date=entry.date,
            )
            obj.ondemand = entry.nv
        except PodcastEpisodeDataPodstat.DoesNotExist:
            obj = PodcastEpisodeDataPodstat(
                episode=entry.episode,
                date=entry.date,
                downloads=0,
                ondemand=entry.nv,
                last_updated=entry.last_updated,
            )
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0018_auto_20201020_1717"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastEpisodeDataPodstat",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("downloads", models.IntegerField(verbose_name="Downloads")),
                ("ondemand", models.IntegerField(verbose_name="OnDemand")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_podstat",
                        related_query_name="data_podstat",
                        to="okr.podcastepisode",
                        verbose_name="Episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Episoden-Abruf (Podstat)",
                "verbose_name_plural": "Podcast-Episoden-Abrufe (Podstat)",
                "db_table": "podcast_episode_data_podstat",
                "ordering": ["-date", "episode"],
                "unique_together": {("date", "episode")},
            },
        ),
        migrations.RunPython(migrate_podstat),
        migrations.DeleteModel(
            name="PodcastEpisodeDataPodstatDownload",
        ),
        migrations.DeleteModel(
            name="PodcastEpisodeDataPodstatOndemand",
        ),
    ]
