# Generated by Django 3.1.2 on 2020-10-22 10:07

from django.db import migrations, models
import django.db.models.deletion


def fill_podcast_data_history(apps, schema_editor):
    Podcast = apps.get_model("okr", "Podcast")

    if Podcast.objects.all().count() == 0:
        return

    from okr.scrapers.podcasts.spotify_api import spotify_api

    for podcast in Podcast.objects.all():
        spotify_id = podcast.spotify_id
        for data in podcast.data_spotify.all():
            data.listeners = spotify_api.podcast_data(
                spotify_id, "listeners", data.date
            )["total"]
            data.listeners_all_time = spotify_api.podcast_data_all_time(
                spotify_id, "listeners", end=data.date
            )["total"]
            data.save()


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0020_auto_20201021_1655"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PodcastDataSpotifyFollowers",
            new_name="PodcastDataSpotify",
        ),
        migrations.AlterModelTable(
            name="podcastdataspotify",
            table="podcast_data_spotify",
        ),
        migrations.AlterModelOptions(
            name="podcastdataspotify",
            options={
                "ordering": ["-date", "podcast"],
                "verbose_name": "Podcast-Spotify-Nutzer",
                "verbose_name_plural": "Podcast-Spotify-Nutzer",
            },
        ),
        migrations.AddField(
            model_name="podcastdataspotify",
            name="listeners",
            field=models.IntegerField(default=0, verbose_name="Listeners"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="podcastdataspotify",
            name="listeners_all_time",
            field=models.IntegerField(default=0, verbose_name="Listeners (insgesamt)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="podcastdataspotify",
            name="podcast",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_spotify",
                related_query_name="data_spotify",
                to="okr.podcast",
                verbose_name="Podcast",
            ),
        ),
        migrations.RunPython(fill_podcast_data_history),
        migrations.AddField(
            model_name="podcastepisodedataspotify",
            name="listeners_all_time",
            field=models.IntegerField(default=0, verbose_name="Listeners (insgesamt)"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="podcastepisodedataspotify",
            name="listeners",
            field=models.IntegerField(verbose_name="Listeners"),
        ),
    ]
