# Generated by Django 3.1.2 on 2020-10-22 11:58

from django.db import migrations
from django.db.models import Count, Max


def remove_duplicates(apps, schema_editor):
    # Source: https://gist.github.com/victorono/cd9d14b013487b8b22975512225c5b4c
    PodcastDataSpotify = apps.get_model("okr", "PodcastDataSpotify")
    unique_fields = ["date", "podcast"]
    duplicates = (
        PodcastDataSpotify.objects.values(*unique_fields)
        .order_by()
        .annotate(max_id=Max("id"), count_id=Count("id"))
        .filter(count_id__gt=1)
    )

    for duplicate in duplicates:
        (
            PodcastDataSpotify.objects.filter(
                **{x: duplicate[x] for x in unique_fields}
            )
            .exclude(id=duplicate["max_id"])
            .delete()
        )


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0021_auto_20201022_1207"),
    ]

    operations = [
        migrations.RunPython(remove_duplicates),
        migrations.AlterUniqueTogether(
            name="podcastdataspotify",
            unique_together={("date", "podcast")},
        ),
    ]
