# Generated by Django 3.1.2 on 2020-11-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0025_auto_20201109_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisodeDataWebtrekkPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('media_views', models.IntegerField(verbose_name='Medienansichten')),
                ('media_views_complete', models.IntegerField(verbose_name='Medienansichten vollständig')),
                ('playing_time', models.DurationField(help_text='HH:MM:SS', verbose_name='Spieldauer')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Zuletzt upgedated')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_webtrekk_performance', related_query_name='data_webtrekk_performance', to='okr.podcastepisode', verbose_name='Episode')),
            ],
            options={
                'verbose_name': 'Podcast-Episoden-Performance (Webtrekk)',
                'verbose_name_plural': 'Podcast-Episoden-Performance (Webtrekk)',
                'db_table': 'podcast_episode_data_webtrekk_performance',
                'ordering': ['-date', 'episode'],
                'unique_together': {('date', 'episode')},
            },
        ),
    ]
