# Generated by Django 3.1.2 on 2020-11-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0026_podcastepisodedatawebtrekkperformance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="podcast",
            name="feed_url",
            field=models.URLField(
                max_length=1024, unique=True, verbose_name="Feed-URL"
            ),
        ),
    ]
