# Generated by Django 3.1.3 on 2020-11-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0028_auto_20201112_1823"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagemeta",
            name="editorial_update",
            field=models.DateTimeField(null=True, verbose_name="Redaktioneller Stand"),
        ),
    ]
