# Generated by Django 3.1.3 on 2020-11-26 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okr', '0029_auto_20201113_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='podcastdataspotify',
            options={'ordering': ['-date', 'podcast'], 'verbose_name': 'Podcast-Spotify-Nutzer*innen', 'verbose_name_plural': 'Podcast-Spotify-Nutzer*innen'},
        ),
        migrations.AlterField(
            model_name='page',
            name='first_seen',
            field=models.DateField(auto_now=True, help_text='Erstellungsdatum des Datenpunktes', verbose_name='Zuerst gesehen'),
        ),
        migrations.AlterField(
            model_name='page',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Jüngste Aktualisierung des Datenpunktes', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='page',
            name='property',
            field=models.ForeignKey(help_text='Globale ID der Website', on_delete=django.db.models.deletion.CASCADE, related_name='pages', related_query_name='page', to='okr.property', verbose_name='Property'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sophora_id',
            field=models.CharField(help_text='Sophora ID des Nachrichtenartikels', max_length=512, verbose_name='Sophora ID'),
        ),
        migrations.AlterField(
            model_name='page',
            name='sophora_page',
            field=models.IntegerField(help_text='Mehrseitiger Nachrichtenartikel (nur falls zutreffend)', null=True, verbose_name='Sophora-Seite'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.URLField(help_text='URL des Nachrichtenartikels', unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='pagedatagsc',
            name='clicks',
            field=models.IntegerField(help_text='Klicks (pro Tag)', verbose_name='Klicks'),
        ),
        migrations.AlterField(
            model_name='pagedatagsc',
            name='ctr',
            field=models.FloatField(help_text='Click-Through Rate (pro Tag)', verbose_name='CTR'),
        ),
        migrations.AlterField(
            model_name='pagedatagsc',
            name='date',
            field=models.DateField(help_text='Datum der SEO-Daten', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='pagedatagsc',
            name='device',
            field=models.CharField(choices=[('MOBILE', 'Mobil'), ('DESKTOP', 'Desktop'), ('TABLET', 'Tablet')], help_text='Gerätetyp (Mobil, Desktop oder Tablet)', max_length=16, verbose_name='Gerätetyp'),
        ),
        migrations.AlterField(
            model_name='pagedatagsc',
            name='impressions',
            field=models.IntegerField(help_text='Impressions (pro Tag)', verbose_name='Impressions'),
        ),
        migrations.AlterField(
            model_name='pagedatagsc',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Letzte Aktualisierung des Datenpunktes', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='pagedatagsc',
            name='page',
            field=models.ForeignKey(help_text='Globale ID des Nachrichtenartikels', on_delete=django.db.models.deletion.CASCADE, related_name='data_gsc', related_query_name='data_gsc', to='okr.page', verbose_name='Seite'),
        ),
        migrations.AlterField(
            model_name='pagedatagsc',
            name='position',
            field=models.FloatField(help_text='Durchschnittliche Position in den Suchergebnissen', verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='editorial_update',
            field=models.DateTimeField(help_text='Von Redaktion gesetzes Standdatum', null=True, verbose_name='Redaktioneller Stand'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='headline',
            field=models.TextField(help_text='Schlagzeile des Nachrichtenartikels', verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Aktualisierung des Datenpunktes', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='page',
            field=models.ForeignKey(help_text='Globale ID des Nachrichtenartikels', on_delete=django.db.models.deletion.CASCADE, related_name='metas', related_query_name='meta', to='okr.page', unique=True, verbose_name='Seite'),
        ),
        migrations.AlterField(
            model_name='pagemeta',
            name='teaser',
            field=models.TextField(help_text='Teasertext des Nachrichtenartikels', verbose_name='Teaser'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='author',
            field=models.CharField(help_text='Urheber*in des Podcasts', max_length=200, verbose_name='Autor*in'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='description',
            field=models.TextField(help_text='Beschreibungstext des Podcasts', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='feed_url',
            field=models.URLField(help_text='Adresse des RSS-Feeds des Podcasts', max_length=1024, unique=True, verbose_name='Feed-URL'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='image',
            field=models.URLField(help_text='URL zum Coverbild des Podcasts', max_length=1024, verbose_name='Bild'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Datum der letzten Daten-Aktualisierung', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='spotify_id',
            field=models.CharField(help_text='Spotify ID, falls vorhanden', max_length=32, null=True, verbose_name='Spotify ID'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotify',
            name='date',
            field=models.DateField(help_text='Erstellungsdatum des Datenpunkts', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotify',
            name='followers',
            field=models.IntegerField(help_text='Anzahl der Followers des Podcasts', verbose_name='Follower'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotify',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Datum der letzten Daten-Aktualisierung', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotify',
            name='listeners',
            field=models.IntegerField(help_text='Anzahl der Hörer*innen', verbose_name='Listeners'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotify',
            name='listeners_all_time',
            field=models.IntegerField(help_text='Hörer*innen insgesamt', verbose_name='Listeners (insgesamt)'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotify',
            name='listeners_monthly',
            field=models.IntegerField(help_text='Hörer*innen pro Monat', verbose_name='Listeners (monatlich)'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotify',
            name='listeners_weekly',
            field=models.IntegerField(help_text='Hörer*innen pro Woche', verbose_name='Listeners (wöchentlich)'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotify',
            name='podcast',
            field=models.ForeignKey(help_text='Globale ID der Podcast-Reihe', on_delete=django.db.models.deletion.CASCADE, related_name='data_spotify', related_query_name='data_spotify', to='okr.podcast', verbose_name='Podcast ID'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotifyhourly',
            name='date_time',
            field=models.DateTimeField(help_text='Datum und Uhrzeit des Datenpunktes', verbose_name='Zeitpunkt'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotifyhourly',
            name='podcast',
            field=models.ForeignKey(help_text='Globale ID der Podcast-Reihe', on_delete=django.db.models.deletion.CASCADE, related_name='data_spotify_hourly', related_query_name='data_spotify_hourly', to='okr.podcast', verbose_name='Podcast'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotifyhourly',
            name='starts',
            field=models.IntegerField(help_text='Anzahl der Starts', verbose_name='Starts'),
        ),
        migrations.AlterField(
            model_name='podcastdataspotifyhourly',
            name='streams',
            field=models.IntegerField(help_text='Anzahl der Streams', verbose_name='Streams'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='description',
            field=models.TextField(help_text='Beschreibungstext der Folge', verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='duration',
            field=models.DurationField(help_text='Länge der Mediendatei', verbose_name='Länge'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Letzte Aktualisierung des Datenpunktes', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='media',
            field=models.URLField(help_text='URL der Mediendatei', max_length=1024, verbose_name='Media-URL'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='podcast',
            field=models.ForeignKey(help_text='Globale ID der Podcast-Reihe', on_delete=django.db.models.deletion.CASCADE, related_name='episodes', related_query_name='episode', to='okr.podcast', verbose_name='Podcast'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='publication_date_time',
            field=models.DateTimeField(help_text='Veröffentlichungsdatum der Folge', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='spotify_id',
            field=models.CharField(help_text='Spotify ID, falls vorhanden', max_length=32, null=True, verbose_name='Spotify ID'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='title',
            field=models.CharField(help_text='Titel der einzelnen Folge', max_length=400, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='zmdb_id',
            field=models.IntegerField(help_text='ZMDB ID der Mediendatei', unique=True, verbose_name='ZMDB-ID'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatapodstat',
            name='date',
            field=models.DateField(help_text='Datum der Abrufzahlen', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatapodstat',
            name='downloads',
            field=models.IntegerField(help_text='Anzahl der Downloads', verbose_name='Downloads'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatapodstat',
            name='episode',
            field=models.ForeignKey(help_text='Globale ID der Episode', on_delete=django.db.models.deletion.CASCADE, related_name='data_podstat', related_query_name='data_podstat', to='okr.podcastepisode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatapodstat',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Zeitpunkt der Datenaktualisierung', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatapodstat',
            name='ondemand',
            field=models.IntegerField(help_text='Anzahl der Ondemand-Abrufe', verbose_name='OnDemand'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotify',
            name='date',
            field=models.DateField(help_text='Datum der Abrufzahlen', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotify',
            name='episode',
            field=models.ForeignKey(help_text='Globale ID der Episode', on_delete=django.db.models.deletion.CASCADE, related_name='data_spotify', related_query_name='data_spotify', to='okr.podcastepisode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotify',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Zeitpunkt der Datenaktualisierung', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotify',
            name='listeners',
            field=models.IntegerField(help_text='Hörer*innen für den jeweiligen Tag', verbose_name='Listeners'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotify',
            name='listeners_all_time',
            field=models.IntegerField(help_text='Gesamtzahl der Hörer*innen', verbose_name='Listeners (insgesamt)'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotify',
            name='starts',
            field=models.IntegerField(help_text='Anzahl der Starts', verbose_name='Starts'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotify',
            name='streams',
            field=models.IntegerField(help_text='Anzahl der Streams', verbose_name='Streams'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyperformance',
            name='complete',
            field=models.IntegerField(help_text='\tHörer*innen der gesamten Folge', verbose_name='Komplett'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyperformance',
            name='date',
            field=models.DateField(help_text='Datum der Performance-Daten', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyperformance',
            name='episode',
            field=models.ForeignKey(help_text='Globale ID der Episode', on_delete=django.db.models.deletion.CASCADE, related_name='data_spotify_performance', related_query_name='data_spotify_performance', to='okr.podcastepisode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyperformance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Zeitpunkt der Datenaktualisierung', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyperformance',
            name='quartile_1',
            field=models.IntegerField(help_text='Hörer*innen im 1. Viertel der Folge', verbose_name='1. Quartil'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyperformance',
            name='quartile_2',
            field=models.IntegerField(help_text='Hörer*innen im 2. Viertel der Folge', verbose_name='2. Quartil'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyperformance',
            name='quartile_3',
            field=models.IntegerField(help_text='Hörer*innen im 3. Viertel der Folge', verbose_name='3. Quartil'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='age_0_17',
            field=models.IntegerField(help_text='Hörer*innen zwischen 0 und 17', verbose_name='0-17'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='age_18_22',
            field=models.IntegerField(help_text='Hörer*innen zwischen 18 und 22', verbose_name='18-22'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='age_23_27',
            field=models.IntegerField(help_text='Hörer*innen zwischen 23 und 27', verbose_name='23-27'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='age_28_34',
            field=models.IntegerField(help_text='Hörer*innen zwischen 28 und 34', verbose_name='28-34'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='age_35_44',
            field=models.IntegerField(help_text='Hörer*innen zwischen 35 und 44', verbose_name='35-44'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='age_45_59',
            field=models.IntegerField(help_text='Hörer*innen zwischen 45 und 59', verbose_name='45-59'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='age_60_150',
            field=models.IntegerField(help_text='Hörer*innen zwischen 60 und 150', verbose_name='60-150'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='age_unknown',
            field=models.IntegerField(help_text='Hörer*innen ohne Altersangabe', verbose_name='Unbekannt'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='date',
            field=models.DateField(help_text='Datum der Abrufzahlen', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='episode',
            field=models.ForeignKey(help_text='Globale ID der Episode', on_delete=django.db.models.deletion.CASCADE, related_name='data_spotify_user', related_query_name='data_spotify_user', to='okr.podcastepisode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='gender_female',
            field=models.IntegerField(help_text='Anzahl der Hörerinnen', verbose_name='Weiblich'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='gender_male',
            field=models.IntegerField(help_text='Anzahl der Hörer', verbose_name='Männlich'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='gender_non_binary',
            field=models.IntegerField(help_text='Anzahl der non-binary Hörer*innen', verbose_name='Non_binary'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='gender_not_specified',
            field=models.IntegerField(help_text='Hörer*innen ohne Geschlechtsangabe', verbose_name='Nicht angegeben'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedataspotifyuser',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Zeitpunkt der Datenaktualisierung', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatawebtrekkperformance',
            name='date',
            field=models.DateField(help_text='Datum der Performance-Daten', verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatawebtrekkperformance',
            name='episode',
            field=models.ForeignKey(help_text='Globale ID der Episode', on_delete=django.db.models.deletion.CASCADE, related_name='data_webtrekk_performance', related_query_name='data_webtrekk_performance', to='okr.podcastepisode', verbose_name='Episode'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatawebtrekkperformance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Zeitpunkt der Datenaktualisierung', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatawebtrekkperformance',
            name='media_views',
            field=models.IntegerField(help_text='Angefangene Abrufe der Mediendatei', verbose_name='Angefangen'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatawebtrekkperformance',
            name='media_views_complete',
            field=models.IntegerField(help_text='Abgeschlossene Abrufe der Mediendatei', verbose_name='Vollständig'),
        ),
        migrations.AlterField(
            model_name='podcastepisodedatawebtrekkperformance',
            name='playing_time',
            field=models.DurationField(help_text='Abspieldauer der Mediendatei (HH:MM:SS)', verbose_name='Spieldauer'),
        ),
        migrations.AlterField(
            model_name='property',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, help_text='Datum der letzten Datenaktualisierung', verbose_name='Zuletzt upgedated'),
        ),
        migrations.AlterField(
            model_name='property',
            name='url',
            field=models.URLField(help_text='URL der Website', unique=True, verbose_name='URL'),
        ),
    ]
