# Generated by Django 3.1.3 on 2020-12-07 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0030_auto_20201126_1641"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insta",
            name="name",
            field=models.CharField(
                help_text="Name des Accounts", max_length=200, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="insta",
            name="quintly_profile_id",
            field=models.IntegerField(verbose_name="Quintly Profil-ID"),
        ),
        migrations.AlterField(
            model_name="instacollaboration",
            name="collaboration_type",
            field=models.ForeignKey(
                help_text="Bezeichnung der Art von Collaboration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collaboration",
                to="okr.instacollaborationtype",
                verbose_name="Format",
            ),
        ),
        migrations.AlterField(
            model_name="instacollaborationtype",
            name="name",
            field=models.CharField(
                help_text="Bezeichnung der Art von Collaboration",
                max_length=200,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="instainsight",
            name="insta",
            field=models.ForeignKey(
                help_text="Globale ID des Instagram-Accounts",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="insights",
                related_query_name="insight",
                to="okr.insta",
                verbose_name="Instagram-Account",
            ),
        ),
        migrations.AlterField(
            model_name="instainsight",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "Täglich"),
                    ("weekly", "Wöchentlich"),
                    ("monthly", "Monatlich"),
                ],
                help_text="Intervall (täglich, wöchentlich oder monatlich)",
                max_length=10,
                verbose_name="Zeitraum",
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="comments",
            field=models.IntegerField(
                help_text="Anzahl der Kommentare", verbose_name="Kommentare"
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="created_at",
            field=models.DateTimeField(verbose_name="Erstellungsdatum"),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="external_id",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Externe ID"
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="insta",
            field=models.ForeignKey(
                help_text="Globale ID des Instagram-Accounts",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                related_query_name="post",
                to="okr.insta",
                verbose_name="Instagram-Account",
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="likes",
            field=models.IntegerField(
                help_text="Anzahl der Likes", verbose_name="Likes"
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="link",
            field=models.URLField(help_text="URL des Postings", verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="message",
            field=models.TextField(
                help_text="Volltext des Postings", verbose_name="Text"
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="post_type",
            field=models.CharField(
                help_text="Art des Postings (Image, Carousel, etc)",
                max_length=20,
                verbose_name="Typ",
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="caption",
            field=models.TextField(
                help_text="Volltext des Story-Elements", null=True, verbose_name="Text"
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="created_at",
            field=models.DateTimeField(verbose_name="Erstellungszeitpunkt"),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="exits",
            field=models.IntegerField(
                help_text="Anzahl der Ausstiege", verbose_name="Exits"
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="external_id",
            field=models.CharField(
                max_length=25, unique=True, verbose_name="Externe ID"
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="insta",
            field=models.ForeignKey(
                help_text="Globale ID des Instagram-Accounts",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                related_query_name="story",
                to="okr.insta",
                verbose_name="Instagram-Account",
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="link",
            field=models.URLField(
                help_text="URL des Story-Elements", max_length=1024, verbose_name="Link"
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="replies",
            field=models.IntegerField(
                help_text="Anzahl der Antworten", verbose_name="Antworten"
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="story_type",
            field=models.CharField(
                help_text="Art des Story-Elements (Image/Video)",
                max_length=200,
                verbose_name="Typ",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="name",
            field=models.CharField(
                help_text="Name des Accounts", max_length=200, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(
                help_text="Name des Accounts", max_length=200, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="youtube",
            name="name",
            field=models.CharField(
                help_text="Name des Accounts", max_length=200, verbose_name="Name"
            ),
        ),
        migrations.AlterField(
            model_name="youtube",
            name="quintly_profile_id",
            field=models.IntegerField(verbose_name="Quintly Profil-ID"),
        ),
        migrations.AlterField(
            model_name="youtubeagerangeaverageviewduration",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "Täglich"),
                    ("weekly", "Wöchentlich"),
                    ("monthly", "Monatlich"),
                ],
                help_text="Intervall (täglich, wöchentlich, monatlich)",
                max_length=10,
                verbose_name="Zeitraum",
            ),
        ),
        migrations.AlterField(
            model_name="youtubeagerangeaverageviewpercentage",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "Täglich"),
                    ("weekly", "Wöchentlich"),
                    ("monthly", "Monatlich"),
                ],
                help_text="Intervall (täglich, wöchentlich, monatlich)",
                max_length=10,
                verbose_name="Zeitraum",
            ),
        ),
        migrations.AlterField(
            model_name="youtubeagerangeviewspercentage",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "Täglich"),
                    ("weekly", "Wöchentlich"),
                    ("monthly", "Monatlich"),
                ],
                help_text="Intervall (täglich, wöchentlich, monatlich)",
                max_length=10,
                verbose_name="Zeitraum",
            ),
        ),
        migrations.AlterField(
            model_name="youtubeagerangewatchtimepercentage",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "Täglich"),
                    ("weekly", "Wöchentlich"),
                    ("monthly", "Monatlich"),
                ],
                help_text="Intervall (täglich, wöchentlich, monatlich)",
                max_length=10,
                verbose_name="Zeitraum",
            ),
        ),
        migrations.AlterField(
            model_name="youtubeanalytics",
            name="interval",
            field=models.CharField(
                choices=[
                    ("daily", "Täglich"),
                    ("weekly", "Wöchentlich"),
                    ("monthly", "Monatlich"),
                ],
                help_text="Intervall (täglich, wöchentlich, monatlich)",
                max_length=10,
                verbose_name="Zeitraum",
            ),
        ),
        migrations.AlterField(
            model_name="youtubeanalytics",
            name="youtube",
            field=models.ForeignKey(
                help_text="Globale ID des YouTube-Accouts",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytic",
                related_query_name="analytics",
                to="okr.youtube",
                verbose_name="YouTube-Account",
            ),
        ),
        migrations.AlterField(
            model_name="youtubetrafficsource",
            name="youtube",
            field=models.ForeignKey(
                help_text="Globale ID des YouTube-Accounts",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traffic_source",
                related_query_name="traffic_sources",
                to="okr.youtube",
                verbose_name="YouTube-Account",
            ),
        ),
    ]
