# Generated by Django 3.1.3 on 2020-12-07 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0031_auto_20201207_1204"),
        ("okr", "0031_auto_20201127_1556"),
    ]

    operations = []
