# Generated by Django 3.1.3 on 2020-12-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0032_merge_20201207_1207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="url",
            field=models.URLField(
                help_text="URL des Nachrichtenartikels",
                max_length=1024,
                unique=True,
                verbose_name="URL",
            ),
        ),
        migrations.AlterField(
            model_name="sophoranode",
            name="node",
            field=models.CharField(
                help_text='Sophora-Knoten in der Form "/wdr/nachrichten" (ohne trailing slash)',
                max_length=128,
                unique=True,
                verbose_name="Sophora Knoten",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sophoradocumentmeta",
            unique_together={
                (
                    "sophora_document",
                    "headline",
                    "teaser",
                    "document_type",
                    "sophora_id",
                    "node",
                )
            },
        ),
    ]
