# Generated by Django 3.1.4 on 2020-12-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0033_auto_20201207_1207"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastEpisodeDataSpotifyDemographics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum der Abrufzahlen", verbose_name="Datum"
                    ),
                ),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("0-17", "0-17"),
                            ("18-22", "18-22"),
                            ("23-27", "23-27"),
                            ("28-34", "28-34"),
                            ("35-44", "35-44"),
                            ("45-59", "45-59"),
                            ("60-150", "60-150"),
                        ],
                        help_text="Die Altersgruppe, für die dieser Datenpunkt gilt.",
                        max_length=20,
                        verbose_name="Altersgruppe",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("NOT_SPECIFIED", "Nicht Angegeben"),
                            ("MALE", "Männlich"),
                            ("FEMALE", "Weiblich"),
                            ("NON_BINARY", "Non-Binary"),
                        ],
                        help_text="Das Geschlecht, für das dieser Datenpunkt gilt.",
                        max_length=20,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        help_text="Anzahl der Streams dieser Demografie.",
                        verbose_name="Streams",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Zeitpunkt der Datenaktualisierung",
                        verbose_name="Zuletzt upgedated",
                    ),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        help_text="Globale ID der Episode",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_spotify_demographics",
                        related_query_name="data_spotify_demographics",
                        to="okr.podcastepisode",
                        verbose_name="Episode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Episoden-Demografiedaten (Spotify)",
                "verbose_name_plural": "Podcast-Episoden-Demografiedaten (Spotify)",
                "db_table": "podcast_episode_data_spotify_user_experimental",
                "ordering": ["-date", "episode"],
                "unique_together": {("date", "episode", "age_range", "gender")},
            },
        ),
    ]
