# Generated by Django 3.1.4 on 2020-12-09 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0036_podcastepisode_available"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sophoraid",
            options={
                "ordering": ["-created"],
                "verbose_name": "Sophora-ID",
                "verbose_name_plural": "Sophora-IDs",
            },
        ),
        migrations.AddField(
            model_name="page",
            name="sophora_id",
            field=models.ForeignKey(
                help_text="Sophora ID der Seite",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                related_query_name="page",
                to="okr.sophoraid",
                verbose_name="Sophora ID",
            ),
        ),
        migrations.AlterField(
            model_name="sophoradocumentmeta",
            name="sophora_id",
            field=models.ForeignKey(
                help_text="Momentane Sophora ID des Dokuments",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="metas",
                related_query_name="meta",
                to="okr.sophoraid",
                verbose_name="Sophora ID",
            ),
        ),
        migrations.AlterField(
            model_name="sophoraid",
            name="sophora_document",
            field=models.ForeignKey(
                help_text="Das Sophora-Dokument, zu dem diese ID gehört (hat)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sophora_ids",
                related_query_name="sophora_id",
                to="okr.sophoradocument",
                verbose_name="Sophora-Dokument",
            ),
        ),
        migrations.AlterModelTable(
            name="sophoraid",
            table="sophora_id",
        ),
    ]
