# Generated by Django 3.1.4 on 2020-12-10 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0037_auto_20201209_1626"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="sophora_page",
            field=models.IntegerField(
                help_text="Seitennummer bei mehrseitigen Nachrichtenartikeln (nur falls zutreffend)",
                null=True,
                verbose_name="Sophora-Seite",
            ),
        ),
        migrations.AlterField(
            model_name="pagedatagsc",
            name="page",
            field=models.ForeignKey(
                help_text="Globale ID der Online-Seite",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_gsc",
                related_query_name="data_gsc",
                to="okr.page",
                verbose_name="Seite",
            ),
        ),
        migrations.AlterField(
            model_name="podcast",
            name="author",
            field=models.CharField(
                help_text="Autor*in des Podcasts",
                max_length=200,
                verbose_name="Autor*in",
            ),
        ),
        migrations.AlterField(
            model_name="sophoradocumentmeta",
            name="document_type",
            field=models.CharField(
                help_text="Der Beitragstyp des Sophora-Beitrags",
                max_length=64,
                verbose_name="Beitragstyp",
            ),
        ),
    ]
