# Generated by Django 3.1.4 on 2020-12-10 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0039_page_node"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageWebtrekkMeta",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "headline",
                    models.TextField(
                        help_text="Schlagzeile des Nachrichtenartikels",
                        verbose_name="Titel",
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="Extrahierte Get-Parameter der URL",
                        verbose_name="Get-Parameter",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Der Zeitpunkt, an dem dieser Eintrag in der Datenbank angelegt wurde",
                        verbose_name="Zeitpunkt der Erstellung",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Die Seite, der die Webtrekk-Meta Informationen zugeordnet wurden",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webtrekk_metas",
                        related_query_name="webtrekk_meta",
                        to="okr.page",
                        verbose_name="Seite",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seiten-Webtrekk-Meta",
                "verbose_name_plural": "Seiten-Webtrekk-Metas",
                "db_table": "page_webtrekk_meta",
                "ordering": ["-created"],
                "unique_together": {("page", "headline", "query")},
            },
        ),
        migrations.CreateModel(
            name="PageDataWebtrekk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum der Webtrekk-Daten", verbose_name="Datum"
                    ),
                ),
                (
                    "visits",
                    models.IntegerField(
                        help_text="Visits (pro Tag)", verbose_name="Visits"
                    ),
                ),
                (
                    "visits_search",
                    models.IntegerField(
                        help_text="Visits via Suchmaschine (pro Tag)",
                        verbose_name="Visits via Suchmaschine",
                    ),
                ),
                (
                    "impressions",
                    models.IntegerField(
                        help_text="Impressions (pro Tag)", verbose_name="Impressions"
                    ),
                ),
                (
                    "impressions_search",
                    models.IntegerField(
                        help_text="Impressions via Suchmaschine (pro Tag)",
                        verbose_name="Impressions via Suchmaschine",
                    ),
                ),
                (
                    "visits_campaign",
                    models.IntegerField(
                        help_text="Kampagnen-Visits (pro Tag)",
                        verbose_name="Kampagnen-Visits",
                    ),
                ),
                (
                    "visits_campaign_search",
                    models.IntegerField(
                        help_text="Kampagnen-Visits via Suchmaschine (pro Tag)",
                        verbose_name="Kampagnen-Visits via Suchmaschine",
                    ),
                ),
                (
                    "entries",
                    models.IntegerField(
                        help_text="Einstiege (pro Tag)", verbose_name="Einstiege"
                    ),
                ),
                (
                    "entries_search",
                    models.IntegerField(
                        help_text="Einstiege via Suchmaschine (pro Tag)",
                        verbose_name="Einstiege via Suchmaschine",
                    ),
                ),
                (
                    "exits",
                    models.IntegerField(
                        help_text="Ausstiege (pro Tag)", verbose_name="Ausstiege"
                    ),
                ),
                (
                    "exits_search",
                    models.IntegerField(
                        help_text="Ausstiege via Suchmaschine (pro Tag)",
                        verbose_name="Ausstiege via Suchmaschine",
                    ),
                ),
                (
                    "bounces",
                    models.IntegerField(
                        help_text="Bounces (pro Tag)", verbose_name="Bounces"
                    ),
                ),
                (
                    "bounces_search",
                    models.IntegerField(
                        help_text="Bounces via Suchmaschine (pro Tag)",
                        verbose_name="Bounces via Suchmaschine",
                    ),
                ),
                (
                    "length_of_stay",
                    models.DurationField(
                        help_text="Verweildauer (pro Tag)", verbose_name="Verweildauer"
                    ),
                ),
                (
                    "length_of_stay_search",
                    models.DurationField(
                        help_text="Verweildauer via Suchmaschine (pro Tag)",
                        verbose_name="Verweildauer via Suchmaschine",
                    ),
                ),
                (
                    "webtrekk_meta",
                    models.ForeignKey(
                        help_text="Globale ID des Webtrekk-Metas",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_webtrekk",
                        related_query_name="data_webtrekk",
                        to="okr.pagewebtrekkmeta",
                        verbose_name="Webtrekk-Meta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seiten-Daten (Webtrekk)",
                "verbose_name_plural": "Seiten-Daten (Webtrekk)",
                "db_table": "page_data_webtrekk",
                "ordering": ["-date", "-visits"],
                "unique_together": {("date", "webtrekk_meta")},
            },
        ),
    ]
