# Generated by Django 3.1.4 on 2020-12-11 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0040_pagedatawebtrekk_pagewebtrekkmeta"),
        ("okr", "0039_auto_20201211_1035"),
    ]

    operations = []
