# Generated by Django 3.1.4 on 2021-01-13 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0041_merge_20201211_1130"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyDataGSC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        help_text="Globale ID der GSC-Property",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_gsc",
                        related_query_name="data_gsc",
                        to="okr.property",
                        verbose_name="Property",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum der SEO-Daten", verbose_name="Datum"
                    ),
                ),
                (
                    "device",
                    models.CharField(
                        choices=[
                            ("MOBILE", "Mobil"),
                            ("DESKTOP", "Desktop"),
                            ("TABLET", "Tablet"),
                        ],
                        help_text="Gerätetyp (Mobil, Desktop oder Tablet)",
                        max_length=16,
                        verbose_name="Gerätetyp",
                    ),
                ),
                (
                    "clicks",
                    models.IntegerField(
                        help_text="Klicks (pro Tag)", verbose_name="Klicks"
                    ),
                ),
                (
                    "impressions",
                    models.IntegerField(
                        help_text="Impressions (pro Tag)", verbose_name="Impressions"
                    ),
                ),
                (
                    "ctr",
                    models.FloatField(
                        help_text="Click-Through Rate (pro Tag)", verbose_name="CTR"
                    ),
                ),
                (
                    "position",
                    models.FloatField(
                        help_text="Durchschnittliche Position in den Suchergebnissen",
                        verbose_name="Position",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Letzte Aktualisierung des Datenpunktes",
                        verbose_name="Zuletzt upgedated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Property-Daten (GSC)",
                "verbose_name_plural": "Property-Daten (GSC)",
                "db_table": "property_data_gsc",
                "ordering": ["-date", "-clicks"],
                "unique_together": {("date", "property", "device")},
            },
        ),
    ]
