# Generated by Django 3.1.4 on 2021-01-13 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0042_propertydatagsc"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageDataQueryGSC",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        help_text="Globale ID der Online-Seite",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_query_gsc",
                        related_query_name="data_query_gsc",
                        to="okr.page",
                        verbose_name="Seite",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum der SEO-Daten", verbose_name="Datum"
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        help_text="Query (Suchanfrage)", verbose_name="Query"
                    ),
                ),
                (
                    "clicks",
                    models.IntegerField(
                        help_text="Klicks (pro Tag)", verbose_name="Klicks"
                    ),
                ),
                (
                    "impressions",
                    models.IntegerField(
                        help_text="Impressions (pro Tag)", verbose_name="Impressions"
                    ),
                ),
                (
                    "ctr",
                    models.FloatField(
                        help_text="Click-Through Rate (pro Tag)", verbose_name="CTR"
                    ),
                ),
                (
                    "position",
                    models.FloatField(
                        help_text="Durchschnittliche Position in den Suchergebnissen",
                        verbose_name="Position",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Letzte Aktualisierung des Datenpunktes",
                        verbose_name="Zuletzt upgedated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seiten-Query-Performance (GSC)",
                "verbose_name_plural": "Seiten-Query-Performance (GSC)",
                "db_table": "page_data_query_gsc",
                "ordering": ["-date", "-clicks"],
                "unique_together": {("date", "page", "query")},
            },
        ),
    ]
