# Generated by Django 3.1.5 on 2021-01-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0045_auto_20210114_1812"),
    ]

    operations = [
        migrations.AddField(
            model_name="sophoradocumentmeta",
            name="word_count",
            field=models.IntegerField(
                help_text="Anzahl der Wörter im Fließtext (incl. Zwischenüberschriften)",
                null=True,
                verbose_name="Word Count",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sophoradocumentmeta",
            unique_together={
                (
                    "sophora_document",
                    "headline",
                    "teaser",
                    "word_count",
                    "document_type",
                    "sophora_id",
                    "node",
                )
            },
        ),
    ]
