# Generated by Django 3.1.5 on 2021-03-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0046_auto_20210114_2214"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="first_seen",
            field=models.DateField(
                auto_now_add=True,
                help_text="Erstellungsdatum des Datenpunktes",
                verbose_name="Zuerst gesehen",
            ),
        ),
        migrations.AlterField(
            model_name="pagewebtrekkmeta",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Der Zeitpunkt, an dem dieser Eintrag in der Datenbank angelegt wurde",
                verbose_name="Zeitpunkt der Erstellung",
            ),
        ),
        migrations.AlterField(
            model_name="sophoradocument",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Der Zeitpunkt, an dem dieser Eintrag in der Datenbank angelegt wurde",
                verbose_name="Zeitpunkt der Erstellung",
            ),
        ),
        migrations.AlterField(
            model_name="sophoradocumentmeta",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Der Zeitpunkt, an dem diese Metadaten abgerufen wurden",
                verbose_name="Zeitpunkt der Erstellung",
            ),
        ),
        migrations.AlterField(
            model_name="sophoraid",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Der Zeitpunkt, an dem dieser Eintrag in der Datenbank angelegt wurde",
                verbose_name="Zeitpunkt der Erstellung",
            ),
        ),
    ]
