# Generated by Django 3.1.5 on 2021-03-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0047_auto_20210308_1629"),
    ]

    operations = [
        migrations.CreateModel(
            name="SophoraKeyword",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.TextField(
                        help_text="Das Keyword", unique=True, verbose_name="Keyword"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Der Zeitpunkt, zu dem dieses Keyword erstmals im Intelligence Layer erfasst wurde.",
                        verbose_name="Zeitpunkt der Erst-Erfassung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sophora-Keyword",
                "verbose_name_plural": "Sophora-Keywords",
                "db_table": "sophora_keyword",
                "ordering": ["-first_seen"],
            },
        ),
        migrations.AddField(
            model_name="sophoradocumentmeta",
            name="keywords",
            field=models.ManyToManyField(
                db_table="sophora_document_meta_sophora_keyword",
                help_text="Die Keywords, mit denen das Sophora-Dokument zu diesem Zeitpunkt getaggt war",
                related_name="metas",
                related_query_name="meta",
                to="okr.SophoraKeyword",
                verbose_name="Keywords",
            ),
        ),
        migrations.AddField(
            model_name='sophoradocumentmeta',
            name='keywords_list',
            field=models.TextField(blank=True, help_text='Eine Liste der verwendeten Keywords', verbose_name='Keywords-Liste'),
        ),
        migrations.AlterUniqueTogether(
            name='sophoradocumentmeta',
            unique_together={('sophora_document', 'keywords_list', 'headline', 'teaser', 'word_count', 'document_type', 'sophora_id', 'node')},
        ),
    ]
