# Generated by Django 3.1.5 on 2021-03-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0047_auto_20210308_1629"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "itunes_category",
                    models.CharField(
                        help_text="Die iTunes Category.",
                        max_length=256,
                        unique=True,
                        verbose_name="iTunes Category",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Der Zeitpunkt, zu dem diese Category erstmals im Intelligence Layer erfasst wurde.",
                        verbose_name="Zeitpunkt der Erst-Erfassung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Category",
                "verbose_name_plural": "Podcast-Categories",
                "db_table": "podcast_category",
                "ordering": ["-first_seen"],
            },
        ),
        migrations.AddField(
            model_name="podcast",
            name="itunes_categories",
            field=models.ManyToManyField(
                db_table="podcast_podcast_category",
                help_text="Die für den Podcast vergebenen iTunes Categories",
                related_name="categories",
                related_query_name="category",
                to="okr.PodcastCategory",
                verbose_name="iTunes Categories",
            ),
        ),
    ]
