# Generated by Django 3.1.5 on 2021-03-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0047_auto_20210308_1629"),
    ]

    operations = [
        migrations.CreateModel(
            name="SophoraKeywords",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="Das Keyword", max_length=512, verbose_name="Keyword"
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Der Zeitpunkt, zu dem dieses Keyword erstmals im Intelligence Layer erfasst wurde.",
                        verbose_name="Zeitpunkt der Erst-Erfassung",
                    ),
                ),
                (
                    "sophora_documents",
                    models.ManyToManyField(
                        db_table="sophora_document_meta_keywords",
                        help_text="Die Sophora-Dokumente, die dieses Keyword nutzen.",
                        related_name="keywords",
                        related_query_name="keyword",
                        to="okr.SophoraDocument",
                        verbose_name="Sophora-Dokumente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sophora-Keywords",
                "verbose_name_plural": "Sophora-Keywords",
                "db_table": "sophora_keywords",
                "ordering": ["-first_seen"],
                "unique_together": {("keyword", "first_seen")},
            },
        ),
    ]
