# Generated by Django 3.1.7 on 2021-03-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0049_auto_20210310_2321"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.TextField(
                        help_text="Manuell vergebene Kategorie.",
                        unique=True,
                        verbose_name="Kategorie",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Der Zeitpunkt, zu dem diese Kategorie angelegt wurde.",
                        verbose_name="Zeitpunkt der Erstellung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Kategorie",
                "verbose_name_plural": "Podcast-Kategorien",
                "db_table": "podcast_category",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="podcast",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                db_table="podcast_podcast_category",
                help_text="Die für den Podcast hier manuell vergebenen Kategorien",
                related_name="podcasts",
                related_query_name="podcast",
                to="okr.PodcastCategory",
                verbose_name="Kategorien",
            ),
        ),
    ]
