# Generated by Django 3.1.7 on 2021-03-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0049_auto_20210310_2321"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastManualCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manual_category",
                    models.TextField(
                        help_text="Manuell vergebene Kategorie.",
                        unique=True,
                        verbose_name="Manuelle Kategorie",
                    ),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Der Zeitpunkt, zu dem diese Kategorie erstmals im Intelligence Layer gespeichert wurde.",
                        verbose_name="Zeitpunkt der Erst-Erfassung",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcasts manuelle Kategorie",
                "verbose_name_plural": "Podcasts manuelle Kategorien",
                "db_table": "podcast_manual_category",
                "ordering": ["-first_seen"],
            },
        ),
        migrations.AddField(
            model_name="podcast",
            name="manual_categories",
            field=models.ManyToManyField(
                db_table="podcast_podcast_manual_category",
                help_text="Die für den Podcast hier manuell vergebenen Kategorien",
                related_name="categories",
                related_query_name="category",
                to="okr.PodcastManualCategory",
                verbose_name="Manuelle Kategorien",
            ),
        ),
    ]
