# Generated by Django 3.1.7 on 2021-03-22 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "okr",
            "0051_tiktok_tiktokchallenge_tiktokdata_tiktokhashtag_tiktokpost_tiktoktag",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="podcastepisode",
            name="last_available_date_time",
            field=models.DateTimeField(
                help_text="Zeitpunkt, zu dem die Episode zuletzt im Feed gesehen wurde",
                null=True,
                verbose_name="Zuletzt verfügbar",
            ),
        ),
    ]
