# Generated by Django 3.1.7 on 2021-03-23 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0052_podcastepisode_last_available_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="itunes_url",
            field=models.TextField(
                help_text="URL im iTunes Podcast Verzeichnis",
                null=True,
                verbose_name="iTunes URL",
            ),
        ),
        migrations.CreateModel(
            name="PodcastITunesReviews",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "podcast",
                    models.ForeignKey(
                        help_text="Globale ID der Podcast-Reihe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_itunes_reviews",
                        related_query_name="data_itunes_review",
                        to="okr.podcast",
                        verbose_name="Podcast ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Erstellungsdatum des Datenpunkts",
                        verbose_name="Datum",
                    ),
                ),
                (
                    "ratings_average",
                    models.FloatField(
                        blank=True,
                        help_text="Durchschnitt der User*innen-Ratings",
                        verbose_name="Ratings Durchschnitt",
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(
                        help_text="Gesamtzahl der Reviews des Podcasts",
                        null=True,
                        verbose_name="Anzahl Reviews",
                    ),
                ),
                (
                    "reviews",
                    models.TextField(
                        blank=True,
                        help_text="Einzelne Reviews zum Podcast (JSON)",
                        verbose_name="Reviews",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum der letzten Daten-Aktualisierung",
                        verbose_name="Zuletzt upgedated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Review bei iTunes",
                "verbose_name_plural": "Podcast-Reviews bei iTunes",
                "db_table": "podcast_itunes_reviews",
                "ordering": ["-date", "podcast"],
                "unique_together": {("date", "podcast")},
            },
        ),
    ]
