# Generated by Django 3.1.7 on 2021-03-23 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0052_podcastepisode_last_available_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="podcast",
            name="itunes_url",
            field=models.TextField(
                help_text="URL im iTunes Podcast Verzeichnis",
                null=True,
                verbose_name="iTunes URL",
            ),
        ),
        migrations.CreateModel(
            name="PodcastITunesReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "podcast",
                    models.ForeignKey(
                        help_text="Globale ID der Podcast-Reihe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_itunes_reviews",
                        related_query_name="data_itunes_review",
                        to="okr.podcast",
                        verbose_name="Podcast ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Erstellungsdatum des Reviews", verbose_name="Datum"
                    ),
                ),
                (
                    "author",
                    models.TextField(
                        help_text="Verfasser*in des Reviews", verbose_name="Autor*in"
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        blank=True, help_text="Titel des Reviews", verbose_name="Titel"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        help_text="Volltext des Reviews",
                        verbose_name="Text",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        help_text="Sterne-Rating des Reviews", verbose_name="Rating"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum der letzten Daten-Aktualisierung",
                        verbose_name="Zuletzt upgedated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Review bei iTunes",
                "verbose_name_plural": "Podcast-Reviews bei iTunes",
                "db_table": "podcast_itunes_review",
                "ordering": ["-date", "podcast"],
                "unique_together": {("podcast", "author")},
            },
        ),
        migrations.CreateModel(
            name="PodcastITunesRating",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "podcast",
                    models.ForeignKey(
                        help_text="Globale ID der Podcast-Reihe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_itunes_ratings",
                        related_query_name="data_itunes_rating",
                        to="okr.podcast",
                        verbose_name="Podcast ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Erstellungsdatum des Datenpunkts",
                        verbose_name="Datum",
                    ),
                ),
                (
                    "ratings_average",
                    models.FloatField(
                        blank=True,
                        help_text="Durchschnitt der User*innen-Ratings",
                        verbose_name="Ratings Durchschnitt",
                    ),
                ),
                (
                    "ratings_count",
                    models.IntegerField(
                        help_text="Gesamtzahl der Ratings des Podcasts",
                        null=True,
                        verbose_name="Anzahl Ratings",
                    ),
                ),
                (
                    "ratings_1_stars",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Anteil der Ratings mit 1 Stern",
                        max_digits=3,
                        null=True,
                        verbose_name="Anteil 1 Stern",
                    ),
                ),
                (
                    "ratings_2_stars",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Anteil der Ratings mit 2 Sternen",
                        max_digits=3,
                        null=True,
                        verbose_name="Anteil 2 Sterne",
                    ),
                ),
                (
                    "ratings_3_stars",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Anteil der Ratings mit 3 Sternen",
                        max_digits=3,
                        null=True,
                        verbose_name="Anteil 3 Sterne",
                    ),
                ),
                (
                    "ratings_4_stars",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Anteil der Ratings mit 4 Sternen",
                        max_digits=3,
                        null=True,
                        verbose_name="Anteil 4 Sterne",
                    ),
                ),
                (
                    "ratings_5_stars",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Anteil der Ratings mit 5 Sternen",
                        max_digits=3,
                        null=True,
                        verbose_name="Anteil 5 Sterne",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum der letzten Daten-Aktualisierung",
                        verbose_name="Zuletzt upgedated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Rating bei iTunes",
                "verbose_name_plural": "Podcast-Ratings bei iTunes",
                "db_table": "podcast_itunes_rating",
                "ordering": ["-date", "podcast"],
                "unique_together": {("date", "podcast")},
            },
        ),
    ]
