# Generated by Django 3.1.7 on 2021-03-24 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0053_auto_20210323_2229"),
    ]

    operations = [
        migrations.CreateModel(
            name="PodcastDataWebtrekkPicker",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "podcast",
                    models.ForeignKey(
                        help_text="Globale ID der Podcast-Reihe",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_webtrekk_picker",
                        related_query_name="data_webtrekk_picker",
                        to="okr.podcast",
                        verbose_name="Podcast ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum des Datenpunkts", verbose_name="Datum"
                    ),
                ),
                ("visits", models.IntegerField(verbose_name="Visits")),
                (
                    "visits_campaign",
                    models.IntegerField(verbose_name="Kampagnen-Visits"),
                ),
                ("exits", models.IntegerField(verbose_name="Ausstiege")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Datum der letzten Daten-Aktualisierung",
                        verbose_name="Zuletzt upgedated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Podcast-Daten (Picker via Webtrekk)",
                "verbose_name_plural": "Podcast-Daten (Picker via Webtrekk)",
                "db_table": "podcast_data_webtrekk_picker",
                "ordering": ["-date", "podcast"],
                "unique_together": {("date", "podcast")},
            },
        ),
    ]
