# Generated by Django 3.1.7 on 2021-03-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0054_podcastdatawebtrekkpicker"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomKeyResult",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("abteilung", "Abteilung"),
                            ("allgemein", "Allgemein"),
                            ("app", "App"),
                            ("clubhouse", "Clubhouse"),
                            ("facebook", "Facebook"),
                            ("flash_briefing", "Flash-Briefing"),
                            ("hauptabteilung", "Hauptabteilung"),
                            ("hoerfunk_sendung", "Hörfunk-Sendung"),
                            ("instagram", "Instagram"),
                            ("messenger", "Messenger"),
                            ("online", "Online"),
                            ("podcast", "Podcast"),
                            ("skill", "Skill"),
                            ("snapchat", "Snapchat"),
                            ("sonstiges", "Sonstiges"),
                            ("team", "Team"),
                            ("tiktok", "TikTok"),
                            ("tv_sendung", "TV-Sendung"),
                            ("twitter", "Twitter"),
                            ("videotext", "Videotext"),
                            ("youtube", "YouTube"),
                            ("zulieferung", "Zulieferung"),
                        ],
                        help_text="Produkt-Typ für die Kennzahl.",
                        max_length=20,
                        verbose_name="Produkt-Typ",
                    ),
                ),
                (
                    "product_name",
                    models.TextField(
                        help_text="Produkt-Name (Beispiel: 0630 by WDR aktuell).",
                        verbose_name="Produkt-Name",
                    ),
                ),
                (
                    "key_result",
                    models.TextField(
                        help_text="Kennzahl (Beispiel: Anzahl Nachrichten pro Woche).",
                        verbose_name="Kennzahl",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beschreibung"),
                ),
                (
                    "key_result_type",
                    models.CharField(
                        choices=[("text", "Text"), ("integer", "Zahl")],
                        help_text="Art der Kennzahl.",
                        max_length=10,
                        verbose_name="Kennzahlen-Typ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manuelle Kennzahl-Definition",
                "verbose_name_plural": "Manuelle Kennzahl-Definitionen",
                "db_table": "custom_key_result",
                "ordering": ["product_type", "product_name"],
            },
        ),
        migrations.CreateModel(
            name="CustomKeyResultRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key_result",
                    models.ForeignKey(
                        help_text="Bezeichnung der manuell angelegten Kennzahl.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        related_query_name="record",
                        to="okr.customkeyresult",
                        verbose_name="Kennzahl",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum des manuellen Daten-Eintrags.",
                        verbose_name="Datum des Eintrags",
                    ),
                ),
                (
                    "value_integer",
                    models.IntegerField(
                        null=True,
                        verbose_name="Wert",
                        help_text="Der Wert der Kennzahl als Zahl.",
                    ),
                ),
                (
                    "value_text",
                    models.TextField(
                        null=True,
                        verbose_name="Wert",
                        help_text="Der Wert der Kennzahl als Text.",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="Notiz")),
            ],
            options={
                "verbose_name": "Manuelle Kennzahl",
                "verbose_name_plural": "Manuelle Kennzahlen",
                "db_table": "custom_key_result_record",
                "ordering": ["-date", "key_result"],
                "unique_together": {("key_result", "date")},
            },
        ),
    ]
