# Generated by Django 3.1.7 on 2021-04-12 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0056_auto_20210331_1749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sophorakeyword",
            name="first_seen",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Der Zeitpunkt, zu dem dieses Keyword erstmals im Data Warehouse erfasst wurde.",
                verbose_name="Zeitpunkt der Erst-Erfassung",
            ),
        ),
    ]
