# Generated by Django 3.2 on 2021-04-13 13:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0057_auto_20210412_1640"),
        ("okr", "0057_auto_20210412_2207"),
    ]

    operations = []
