# Generated by Django 3.2 on 2021-04-13 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0058_merge_0057_auto_20210412_1640_0057_auto_20210412_2207"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="sophoradocumentmeta",
            unique_together={
                (
                    "sophora_document",
                    "editorial_update",
                    "keywords_list",
                    "headline",
                    "teaser",
                    "word_count",
                    "document_type",
                    "sophora_id",
                    "node",
                )
            },
        ),
    ]
