# Generated by Django 3.2 on 2021-04-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0059_alter_sophoradocumentmeta_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facebook",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name des Objekts",
                        max_length=200,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "quintly_profile_id",
                    models.IntegerField(verbose_name="Quintly Profil-ID"),
                ),
            ],
            options={
                "verbose_name": "Facebook-Account",
                "verbose_name_plural": "Facebook-Accounts",
                "db_table": "facebook",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FacebookPost",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Erstellungsdatum")),
                (
                    "post_type",
                    models.CharField(
                        help_text="Art des Postings", max_length=20, verbose_name="Typ"
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Externe ID"
                    ),
                ),
                (
                    "link",
                    models.URLField(help_text="URL des Postings", verbose_name="Link"),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Volltext des Postings",
                        verbose_name="Text",
                        null=True,
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        help_text="Anzahl der Likes", verbose_name="Likes 👍"
                    ),
                ),
                (
                    "love",
                    models.IntegerField(
                        help_text="Anzahl der Love-Reaktionen", verbose_name="Love ❤️"
                    ),
                ),
                (
                    "wow",
                    models.IntegerField(
                        help_text="Anzahl der WOW-Reaktionen", verbose_name="WOW 😯"
                    ),
                ),
                (
                    "haha",
                    models.IntegerField(
                        help_text="Anzahl der Haha-Reaktionen", verbose_name="Haha 😂"
                    ),
                ),
                (
                    "sad",
                    models.IntegerField(
                        help_text="Anzahl der Traurig-Reaktionen",
                        verbose_name="Traurig 😢",
                    ),
                ),
                (
                    "angry",
                    models.IntegerField(
                        help_text="Anzahl der Wütend-Reaktionen",
                        verbose_name="Wütend 😡",
                    ),
                ),
                (
                    "comments",
                    models.IntegerField(
                        help_text="Anzahl der Kommentare", verbose_name="Kommentare"
                    ),
                ),
                (
                    "shares",
                    models.IntegerField(
                        help_text="Anzahl der Shares", verbose_name="Shares"
                    ),
                ),
                (
                    "impressions_unique",
                    models.IntegerField(verbose_name="Impressions (Unique)"),
                ),
                ("is_published", models.BooleanField(verbose_name="Veröffentlicht")),
                ("is_hidden", models.BooleanField(verbose_name="Versteckt")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "facebook",
                    models.ForeignKey(
                        help_text="Globale ID des Facebook-Accounts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        related_query_name="post",
                        to="okr.facebook",
                        verbose_name="Facebook-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facebook-Post",
                "verbose_name_plural": "Facebook-Posts",
                "db_table": "facebook_post",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FacebookInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Täglich"),
                            ("weekly", "Wöchentlich"),
                            ("monthly", "Monatlich"),
                        ],
                        help_text="Intervall (täglich, wöchentlich oder monatlich)",
                        max_length=10,
                        verbose_name="Zeitraum",
                    ),
                ),
                ("fans", models.IntegerField(verbose_name="Fans")),
                ("follows", models.IntegerField(verbose_name="Follower")),
                (
                    "impressions_unique",
                    models.IntegerField(verbose_name="Impressions (Unique)"),
                ),
                (
                    "fans_online_per_day",
                    models.IntegerField(null=True, verbose_name="Fans online pro Tag"),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "facebook",
                    models.ForeignKey(
                        help_text="Globale ID des Facebook-Accounts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        related_query_name="insight",
                        to="okr.facebook",
                        verbose_name="Facebook-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facebook-Insight",
                "verbose_name_plural": "Facebook-Insights",
                "db_table": "facebook_insights",
                "ordering": ["-date"],
                "unique_together": {("facebook", "date", "interval")},
            },
        ),
    ]
