# Generated by Django 3.2 on 2021-04-30 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0060_facebook_facebookinsight_facebookpost"),
    ]

    operations = [
        migrations.CreateModel(
            name="Twitter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name des Objekts",
                        max_length=200,
                        unique=True,
                        verbose_name="Name",
                    ),
                ),
                (
                    "quintly_profile_id",
                    models.IntegerField(verbose_name="Quintly Profil-ID"),
                ),
            ],
            options={
                "verbose_name": "Twitter-Account",
                "verbose_name_plural": "Twitter-Accounts",
                "db_table": "twitter",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Erstellungsdatum")),
                (
                    "tweet_type",
                    models.CharField(
                        help_text="Art des Tweets",
                        max_length=20,
                        verbose_name="Typ",
                        null=True,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=64, unique=True, verbose_name="Externe ID"
                    ),
                ),
                (
                    "link",
                    models.URLField(help_text="URL des Postings", verbose_name="Link"),
                ),
                ("is_retweet", models.BooleanField(verbose_name="Retweet")),
                (
                    "message",
                    models.TextField(
                        help_text="Volltext des Tweets", null=True, verbose_name="Text"
                    ),
                ),
                (
                    "favs",
                    models.IntegerField(
                        help_text="Anzahl der Favorites", verbose_name="Favorites"
                    ),
                ),
                (
                    "retweets",
                    models.IntegerField(
                        help_text="Anzahl der Retweets", verbose_name="Retweets"
                    ),
                ),
                (
                    "replies",
                    models.IntegerField(
                        help_text="Anzahl der Antworten", verbose_name="Antworten"
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "twitter",
                    models.ForeignKey(
                        help_text="Globale ID des Twitter-Accounts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweets",
                        related_query_name="tweet",
                        to="okr.twitter",
                        verbose_name="Twitter-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tweet",
                "verbose_name_plural": "Tweets",
                "db_table": "tweet",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwitterInsight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "interval",
                    models.CharField(
                        choices=[
                            ("daily", "Täglich"),
                            ("weekly", "Wöchentlich"),
                            ("monthly", "Monatlich"),
                        ],
                        help_text="Intervall (täglich, wöchentlich oder monatlich)",
                        max_length=10,
                        verbose_name="Zeitraum",
                    ),
                ),
                ("followers", models.IntegerField(verbose_name="Follower")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "twitter",
                    models.ForeignKey(
                        help_text="Globale ID des Twitter-Accounts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        related_query_name="insight",
                        to="okr.twitter",
                        verbose_name="Twitter-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twitter-Insight",
                "verbose_name_plural": "Twitter-Insights",
                "db_table": "twitter_insights",
                "ordering": ["-date"],
                "unique_together": {("twitter", "date", "interval")},
            },
        ),
    ]
