# Generated by Django 3.2 on 2021-04-30 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0061_tweet_twitter_twitterinsight"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubeanalytics",
            name="subscribers",
            field=models.IntegerField(null=True, verbose_name="Abonnenten"),
        ),
        migrations.AddField(
            model_name="youtubeanalytics",
            name="subscribers_change",
            field=models.IntegerField(null=True, verbose_name="Veränderung Abonnenten"),
        ),
    ]
