# Generated by Django 3.2.4 on 2021-06-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0064_auto_20210616_2152"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="page",
            name="sophora_document",
        ),
    ]
