# Generated by Django 3.2.4 on 2021-07-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0065_remove_page_sophora_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="facebook",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Entscheidet darüber, ob die Scraper für dieses Objekt aktiv sind",
                verbose_name="Aktiv",
            ),
        ),
        migrations.AddField(
            model_name="insta",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Entscheidet darüber, ob die Scraper für dieses Objekt aktiv sind",
                verbose_name="Aktiv",
            ),
        ),
        migrations.AddField(
            model_name="podcast",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Entscheidet darüber, ob die Scraper für dieses Objekt aktiv sind",
                verbose_name="Aktiv",
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Entscheidet darüber, ob die Scraper für dieses Objekt aktiv sind",
                verbose_name="Aktiv",
            ),
        ),
        migrations.AddField(
            model_name="tiktok",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Entscheidet darüber, ob die Scraper für dieses Objekt aktiv sind",
                verbose_name="Aktiv",
            ),
        ),
        migrations.AddField(
            model_name="twitter",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Entscheidet darüber, ob die Scraper für dieses Objekt aktiv sind",
                verbose_name="Aktiv",
            ),
        ),
        migrations.AddField(
            model_name="youtube",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Entscheidet darüber, ob die Scraper für dieses Objekt aktiv sind",
                verbose_name="Aktiv",
            ),
        ),
    ]
