# Generated by Django 3.2.4 on 2021-07-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0066_auto_20210719_1622"),
    ]

    operations = [
        migrations.AddField(
            model_name="instapost",
            name="quintly_import_time",
            field=models.DateTimeField(
                help_text="Stand der Daten bei Quintly",
                null=True,
                verbose_name="Import Time",
            ),
        ),
        migrations.AddField(
            model_name="instapost",
            name="saved",
            field=models.IntegerField(
                help_text="Anzahl der Saves", null=True, verbose_name="Saves"
            ),
        ),
        migrations.AddField(
            model_name="instapost",
            name="video_views",
            field=models.IntegerField(
                help_text="Video-Views (3 sec oder mehr)",
                null=True,
                verbose_name="Likes",
            ),
        ),
        migrations.AddField(
            model_name="instastory",
            name="quintly_import_time",
            field=models.DateTimeField(
                help_text="Stand der Daten bei Quintly",
                null=True,
                verbose_name="Import Time",
            ),
        ),
        migrations.AddField(
            model_name="instastory",
            name="taps_back",
            field=models.IntegerField(
                help_text="Anzahl der back Taps", null=True, verbose_name="Taps back"
            ),
        ),
        migrations.AddField(
            model_name="instastory",
            name="taps_forward",
            field=models.IntegerField(
                help_text="Anzahl der forward Taps",
                null=True,
                verbose_name="Taps forward",
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="comments",
            field=models.IntegerField(
                help_text="Anzahl der Kommentare", null=True, verbose_name="Kommentare"
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="impressions",
            field=models.IntegerField(null=True, verbose_name="Impressions"),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="likes",
            field=models.IntegerField(
                help_text="Anzahl der Likes", null=True, verbose_name="Likes"
            ),
        ),
        migrations.AlterField(
            model_name="instapost",
            name="reach",
            field=models.IntegerField(null=True, verbose_name="Reichweite"),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="exits",
            field=models.IntegerField(
                help_text="Anzahl der Ausstiege", null=True, verbose_name="Exits"
            ),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="impressions",
            field=models.IntegerField(null=True, verbose_name="Impressions"),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="reach",
            field=models.IntegerField(null=True, verbose_name="Reichweite"),
        ),
        migrations.AlterField(
            model_name="instastory",
            name="replies",
            field=models.IntegerField(
                help_text="Anzahl der Antworten", null=True, verbose_name="Antworten"
            ),
        ),
        migrations.CreateModel(
            name="InstaIGTV",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=25, unique=True, verbose_name="Externe ID"
                    ),
                ),
                ("created_at", models.DateTimeField(verbose_name="Erstellungsdatum")),
                (
                    "message",
                    models.TextField(
                        help_text="Beschreibungstext des IGTV Videos",
                        verbose_name="Text",
                    ),
                ),
                (
                    "video_title",
                    models.TextField(
                        help_text="Titel des IGTV Videos", verbose_name="Titel"
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        help_text="Anzahl der Likes", null=True, verbose_name="Likes"
                    ),
                ),
                (
                    "comments",
                    models.IntegerField(
                        help_text="Anzahl der Kommentare",
                        null=True,
                        verbose_name="Kommentare",
                    ),
                ),
                ("reach", models.IntegerField(null=True, verbose_name="Reichweite")),
                (
                    "impressions",
                    models.IntegerField(null=True, verbose_name="Impressions"),
                ),
                (
                    "saved",
                    models.IntegerField(
                        help_text="Anzahl der Saves", null=True, verbose_name="Saves"
                    ),
                ),
                (
                    "video_views",
                    models.IntegerField(
                        help_text="Video-Views (3 sec oder mehr)",
                        null=True,
                        verbose_name="Likes",
                    ),
                ),
                (
                    "link",
                    models.URLField(help_text="URL des Postings", verbose_name="Link"),
                ),
                (
                    "quintly_import_time",
                    models.DateTimeField(
                        help_text="Stand der Daten bei Quintly",
                        null=True,
                        verbose_name="Import Time",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "insta",
                    models.ForeignKey(
                        help_text="Globale ID des Instagram-Accounts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="igtv_videos",
                        related_query_name="igtv_video",
                        to="okr.insta",
                        verbose_name="Instagram-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram IGTV Video",
                "verbose_name_plural": "Instagram IGTV Videos",
                "db_table": "instagram_tv_video",
                "ordering": ["-created_at"],
            },
        ),
    ]
