# Generated by Django 3.2.4 on 2021-07-21 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0067_auto_20210720_2153"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instapost",
            name="video_views",
            field=models.IntegerField(
                help_text="Video-Views (3 sec oder mehr)",
                null=True,
                verbose_name="Video-Views",
            ),
        ),
        migrations.DeleteModel(
            name="InstaCollaboration",
        ),
        migrations.DeleteModel(
            name="InstaCollaborationType",
        ),
    ]
