# Generated by Django 3.2.4 on 2021-07-23 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0068_snapchatshow_snapchatshowinsight_snapchatshowstory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SnapchatShowSnap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        help_text="The ID of this snap.", max_length=32, unique=True
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        help_text="The ID of the story this snap belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snaps",
                        related_query_name="snap",
                        to="okr.snapchatshowstory",
                        verbose_name="Snapchat Show Story",
                    ),
                ),
                (
                    "name",
                    models.TextField(help_text="The name of this snap.", null=True),
                ),
                (
                    "position",
                    models.IntegerField(
                        help_text="The position of this snap within the story. The first snap has position 1.",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        help_text="The duration of this snap.", null=True
                    ),
                ),
                (
                    "subscribe_options_headline",
                    models.TextField(
                        help_text="The headline of the call to action to subscribe to the show present on this snap.",
                        null=True,
                    ),
                ),
                (
                    "tiles",
                    models.IntegerField(
                        help_text="The number of tiles related to this snap.", null=True
                    ),
                ),
                (
                    "gender_demographics_male",
                    models.IntegerField(
                        help_text="The number of male users who saw this snap.",
                        null=True,
                    ),
                ),
                (
                    "gender_demographics_female",
                    models.IntegerField(
                        help_text="The number of female users who saw this snap.",
                        null=True,
                    ),
                ),
                (
                    "gender_demographics_unknown",
                    models.IntegerField(
                        help_text="The number of users with unknown gender who saw this snap.",
                        null=True,
                    ),
                ),
                (
                    "age_demographics_13_to_17",
                    models.IntegerField(
                        help_text="The number of users in the age group 13 to 17 years who saw this snap.",
                        null=True,
                    ),
                ),
                (
                    "age_demographics_18_to_24",
                    models.IntegerField(
                        help_text="The number of users in the age group 18 to 24 years who saw this snap.",
                        null=True,
                    ),
                ),
                (
                    "age_demographics_25_to_34",
                    models.IntegerField(
                        help_text="The number of users in the age group 25 to 34 years who saw this snap.",
                        null=True,
                    ),
                ),
                (
                    "age_demographics_35_plus",
                    models.IntegerField(
                        help_text="The number of users in the age group 35 and older years who saw this snap.",
                        null=True,
                    ),
                ),
                (
                    "age_demographics_unknown",
                    models.IntegerField(
                        help_text="The number of users with unknown age who saw this snap.",
                        null=True,
                    ),
                ),
                (
                    "view_time",
                    models.DurationField(
                        help_text="The total time this snap was viewed.", null=True
                    ),
                ),
                (
                    "average_view_time_per_user",
                    models.DurationField(
                        help_text="The average time per user this snap was viewed.",
                        null=True,
                    ),
                ),
                (
                    "total_views",
                    models.IntegerField(
                        help_text="The total number of views for this snap.", null=True
                    ),
                ),
                (
                    "unique_viewers",
                    models.IntegerField(
                        help_text="The total number of unique viewers for this snap.",
                        null=True,
                    ),
                ),
                (
                    "unique_completers",
                    models.IntegerField(
                        help_text="The total number of users who completely watched this snap.",
                        null=True,
                    ),
                ),
                (
                    "completion_rate",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The percentage of users who completely watched this snap.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "shares",
                    models.IntegerField(
                        help_text="The total number of shares for this snap.", null=True
                    ),
                ),
                (
                    "unique_sharers",
                    models.IntegerField(
                        help_text="The total number of users sharing this snap.",
                        null=True,
                    ),
                ),
                (
                    "viewers_from_shares",
                    models.IntegerField(
                        help_text="The total number of users viewing this story from a snap.",
                        null=True,
                    ),
                ),
                (
                    "screenshots",
                    models.IntegerField(
                        help_text="The total number of screenshots made of this snap.",
                        null=True,
                    ),
                ),
                (
                    "drop_off_rate",
                    models.DecimalField(
                        decimal_places=5,
                        help_text="The percentage of users that dropped off from this snap to the next.",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "topsnap_view_time",
                    models.DurationField(
                        help_text="The total time topsnaps related to this snap were viewed.",
                        null=True,
                    ),
                ),
                (
                    "topsnap_average_view_time_per_user",
                    models.DurationField(
                        help_text="The average time per user topsnaps related to this snap were viewed.",
                        null=True,
                    ),
                ),
                (
                    "topsnap_total_views",
                    models.IntegerField(
                        help_text="The total number of views for topsnaps related to this snap.",
                        null=True,
                    ),
                ),
                (
                    "topsnap_unique_views",
                    models.IntegerField(
                        help_text="The total number of unique views for topsnaps related to this snap.",
                        null=True,
                    ),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Snapchat Show Snap",
                "verbose_name_plural": "Snapchat Show Snaps",
                "db_table": "snapchat_show_snap",
                "ordering": ["story__start_date_time"],
            },
        ),
    ]
