# Generated by Django 3.2.4 on 2021-07-21 12:53

from time import sleep

from django.db import migrations, models


def delete_non_daily_intervals(apps, schema_editor):
    InstaInsight = apps.get_model("okr", "InstaInsight")

    if InstaInsight.objects.all().count() == 0:
        return

    InstaInsight.objects.exclude(interval="daily").delete()
    sleep(5)


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0068_auto_20210721_0535"),
    ]

    operations = [
        migrations.RunPython(delete_non_daily_intervals),
        migrations.RemoveField(
            model_name="instaigtv",
            name="quintly_import_time",
        ),
        migrations.RemoveField(
            model_name="instapost",
            name="quintly_import_time",
        ),
        migrations.RemoveField(
            model_name="instastory",
            name="quintly_import_time",
        ),
        migrations.AddField(
            model_name="instaigtv",
            name="quintly_last_updated",
            field=models.DateTimeField(
                help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                null=True,
                verbose_name="Zuletzt upgedated (Quintly)",
            ),
        ),
        migrations.AddField(
            model_name="instainsight",
            name="profile_views",
            field=models.IntegerField(null=True, verbose_name="Profilansichten"),
        ),
        migrations.AddField(
            model_name="instainsight",
            name="quintly_last_updated",
            field=models.DateTimeField(
                help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                null=True,
                verbose_name="Zuletzt upgedated (Quintly)",
            ),
        ),
        migrations.AddField(
            model_name="instainsight",
            name="reach_28_days",
            field=models.IntegerField(
                null=True, verbose_name="Reichweite (28 Tage rollierend)"
            ),
        ),
        migrations.AddField(
            model_name="instainsight",
            name="reach_7_days",
            field=models.IntegerField(
                null=True, verbose_name="Reichweite (7 Tage rollierend)"
            ),
        ),
        migrations.AlterField(
            model_name="instainsight",
            name="followers",
            field=models.IntegerField(null=True, verbose_name="Follower"),
        ),
        migrations.AddField(
            model_name="instapost",
            name="quintly_last_updated",
            field=models.DateTimeField(
                help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                null=True,
                verbose_name="Zuletzt upgedated (Quintly)",
            ),
        ),
        migrations.AddField(
            model_name="instastory",
            name="quintly_last_updated",
            field=models.DateTimeField(
                help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                null=True,
                verbose_name="Zuletzt upgedated (Quintly)",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="instainsight",
            unique_together={("insta", "date")},
        ),
        migrations.RemoveField(
            model_name="instainsight",
            name="followers_change",
        ),
        migrations.RemoveField(
            model_name="instainsight",
            name="interval",
        ),
        migrations.RemoveField(
            model_name="instainsight",
            name="posts_change",
        ),
    ]
