# Generated by Django 3.2.5 on 2021-08-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "okr",
            "0068_snapchatshow_snapchatshowinsight_snapchatshowsnap_snapchatshowstory",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="InstaIGTVData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum des Datenpunkts", verbose_name="Datum"
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        help_text="Anzahl der Likes", null=True, verbose_name="Likes"
                    ),
                ),
                (
                    "comments",
                    models.IntegerField(
                        help_text="Anzahl der Kommentare",
                        null=True,
                        verbose_name="Kommentare",
                    ),
                ),
                ("reach", models.IntegerField(null=True, verbose_name="Reichweite")),
                (
                    "impressions",
                    models.IntegerField(null=True, verbose_name="Impressions"),
                ),
                (
                    "saved",
                    models.IntegerField(
                        help_text="Anzahl der Saves", null=True, verbose_name="Saves"
                    ),
                ),
                (
                    "video_views",
                    models.IntegerField(
                        help_text="Video-Views (3 sec oder mehr)",
                        null=True,
                        verbose_name="Likes",
                    ),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "igtv",
                    models.ForeignKey(
                        help_text="Globale ID des IGTV",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        related_query_name="data",
                        to="okr.instaigtv",
                        verbose_name="IGTV",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram IGTV Video-Daten",
                "verbose_name_plural": "Instagram IGTV Video-Daten",
                "db_table": "instagram_tv_video_data",
                "ordering": ["-date"],
                "unique_together": {("igtv", "date")},
            },
        ),
    ]
