# Generated by Django 3.2.4 on 2021-07-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0069_auto_20210721_1453"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstaHourlyFollowers",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        help_text="Datum und Uhrzeit des Datenpunktes",
                        verbose_name="Zeitpunkt",
                    ),
                ),
                (
                    "followers",
                    models.IntegerField(
                        help_text="Anzahl der aktiven Follower",
                        verbose_name="Followers",
                    ),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "insta",
                    models.ForeignKey(
                        help_text="Globale ID des Instagram-Accounts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_hourly_followers",
                        related_query_name="instagram_hourly_followers",
                        to="okr.insta",
                        verbose_name="Instagram-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Hourly Followers",
                "verbose_name_plural": "Instagram  Hourly Followers",
                "db_table": "instagram_hourly_followers",
                "ordering": ["-date_time"],
                "unique_together": {("insta", "date_time")},
            },
        ),
        migrations.CreateModel(
            name="InstaDemographics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("13-17", "13-17"),
                            ("18-24", "18-24"),
                            ("25-34", "25-34"),
                            ("35-44", "35-44"),
                            ("45-54", "45-54"),
                            ("55-64", "55-64"),
                            ("65+", "65+"),
                            ("unknown", "Unbekannt"),
                        ],
                        help_text="Die Altersgruppe, für die dieser Datenpunkt gilt.",
                        max_length=20,
                        verbose_name="Altersgruppe",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Männlich"),
                            ("female", "Weiblich"),
                            ("unknown", "Unbekannt"),
                        ],
                        help_text="Das Geschlecht, für das dieser Datenpunkt gilt.",
                        max_length=20,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "followers",
                    models.IntegerField(
                        help_text="Anzahl der Followers dieser Demografie.",
                        null=True,
                        verbose_name="Followers",
                    ),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "insta",
                    models.ForeignKey(
                        help_text="Globale ID des Instagram-Accounts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_demographics",
                        related_query_name="instagram_demographics",
                        to="okr.insta",
                        verbose_name="Instagram-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Demographics",
                "verbose_name_plural": "Instagram Demographics",
                "db_table": "instagram_demographics",
                "ordering": ["-date"],
                "unique_together": {("insta", "date", "age_range", "gender")},
            },
        ),
    ]
