# Generated by Django 3.2.7 on 2021-09-09 16:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0071_auto_20210907_1603"),
    ]

    operations = [
        migrations.DeleteModel(
            name="YouTubeAgeRangeAverageViewDuration",
        ),
        migrations.DeleteModel(
            name="YouTubeAgeRangeAverageViewPercentage",
        ),
        migrations.DeleteModel(
            name="YouTubeAgeRangeViewsPercentage",
        ),
        migrations.DeleteModel(
            name="YouTubeAgeRangeWatchTimePercentage",
        ),
        migrations.DeleteModel(
            name="YouTubeAnalytics",
        ),
        migrations.DeleteModel(
            name="YouTubeTrafficSource",
        ),
    ]
