# Generated by Django 3.2.7 on 2021-09-09 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0072_auto_20210909_1859"),
    ]

    operations = [
        migrations.CreateModel(
            name="YouTubeVideo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Externe ID"
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        null=True, verbose_name="Veröffentlichungszeitpunkt"
                    ),
                ),
                (
                    "is_livestream",
                    models.BooleanField(
                        help_text="Video als Livestream angelegt",
                        verbose_name="Livestream",
                    ),
                ),
                (
                    "title",
                    models.TextField(
                        help_text="Titel des Videos", verbose_name="Titel"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Beschreibungstext des Videos",
                        verbose_name="Beschreibung",
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        help_text="Länge des Videos", verbose_name="Länge"
                    ),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube",
                    models.ForeignKey(
                        help_text="Globale ID des YouTube-Accouts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        related_query_name="video",
                        to="okr.youtube",
                        verbose_name="YouTube-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube-Video",
                "verbose_name_plural": "YouTube-Videos",
                "db_table": "youtube_video",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideoTrafficSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("0: Direct or unknown", "Direct or unknown"),
                            ("1: YouTube advertising", "YouTube advertising"),
                            ("3: Browse features", "Browse features"),
                            ("4: YouTube channels", "YouTube channels"),
                            ("5: YouTube search", "YouTube search"),
                            ("7: Suggested videos", "Suggested videos"),
                            ("8: Other YouTube features", "Other YouTube features"),
                            ("9: External", "External"),
                            (
                                "11: Video cards and annotations",
                                "Video cards and annotations",
                            ),
                            ("14: Playlists", "Playlists"),
                            ("17: Notifications", "Notifications"),
                            ("18: Playlist pages", "Playlist pages"),
                            (
                                "19: Programming from claimed content",
                                "Programming from claimed content",
                            ),
                            (
                                "20: Interactive video endscreen",
                                "Interactive video endscreen",
                            ),
                            ("23: Stories", "Stories"),
                            ("24: Shorts", "Shorts"),
                            ("25: Product Pages", "Product Pages"),
                            ("26: Hashtag Pages", "Hashtag Pages"),
                            ("27: Sound Pages", "Sound Pages"),
                        ],
                        max_length=40,
                        verbose_name="Source Type",
                    ),
                ),
                ("views", models.IntegerField(verbose_name="Views")),
                ("watch_time", models.DurationField(verbose_name="Sehdauer Gesamt")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube_video",
                    models.ForeignKey(
                        help_text="ID des YouTube-Videos",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_sources",
                        related_query_name="traffic_source",
                        to="okr.youtubevideo",
                        verbose_name="YouTube-Video",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Video Traffic Source",
                "verbose_name_plural": "YouTube Video Traffic Source",
                "db_table": "youtube_video_traffic_source",
                "ordering": ["source_type"],
                "unique_together": {("youtube_video", "source_type")},
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideoSearchTerm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("search_term", models.TextField(verbose_name="Suche")),
                ("views", models.IntegerField(verbose_name="Views")),
                ("watch_time", models.DurationField(verbose_name="Sehdauer Gesamt")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube_video",
                    models.ForeignKey(
                        help_text="ID des YouTube-Videos",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_terms",
                        related_query_name="search_term",
                        to="okr.youtubevideo",
                        verbose_name="YouTube-Video",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Video Search Term",
                "verbose_name_plural": "YouTube Video Search Terms",
                "db_table": "youtube_video_search_term",
                "ordering": ["youtube_video", "search_term"],
                "unique_together": {("youtube_video", "search_term")},
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideoExternalTraffic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Traffic Source")),
                ("views", models.IntegerField(verbose_name="Views")),
                ("watch_time", models.DurationField(verbose_name="Sehdauer Gesamt")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube_video",
                    models.ForeignKey(
                        help_text="ID des YouTube-Videos",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_traffic",
                        related_query_name="external_traffic",
                        to="okr.youtubevideo",
                        verbose_name="YouTube-Video",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Video External Traffic",
                "verbose_name_plural": "YouTube Video External Traffic",
                "db_table": "youtube_video_external_traffic",
                "ordering": ["name"],
                "unique_together": {("youtube_video", "name")},
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideoDemographics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("13-17", "13-17"),
                            ("18-24", "18-24"),
                            ("25-34", "25-34"),
                            ("35-44", "35-44"),
                            ("45-54", "45-54"),
                            ("55-64", "55-64"),
                            ("65+", "65+"),
                        ],
                        help_text="Die Altersgruppe, für die dieser Datenpunkt gilt",
                        max_length=20,
                        verbose_name="Altersgruppe",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Männlich"),
                            ("female", "Weiblich"),
                            ("gender_other", "Andere Geschlechtsangabe"),
                        ],
                        help_text="Das Geschlecht, für das dieser Datenpunkt gilt",
                        max_length=20,
                        verbose_name="Geschlecht",
                    ),
                ),
                (
                    "views_percentage",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=5,
                        null=True,
                        verbose_name="Anteil der Views",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube_video",
                    models.ForeignKey(
                        help_text="ID des YouTube-Videos",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics",
                        related_query_name="demographics",
                        to="okr.youtubevideo",
                        verbose_name="YouTube-Video",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Video Demographics",
                "verbose_name_plural": "YouTube Video Demographics",
                "db_table": "youtube_video_demographics",
                "ordering": ["-date"],
                "unique_together": {("youtube_video", "date", "age_range", "gender")},
            },
        ),
        migrations.CreateModel(
            name="YouTubeVideoAnalytics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "live_or_on_demand",
                    models.CharField(
                        choices=[("live", "Live"), ("on_demand", "On demand")],
                        max_length=10,
                        verbose_name="Live oder on demand",
                    ),
                ),
                ("views", models.IntegerField(verbose_name="Views")),
                ("likes", models.IntegerField(verbose_name="Likes")),
                ("dislikes", models.IntegerField(verbose_name="Dislikes")),
                ("comments", models.IntegerField(verbose_name="Kommentare")),
                ("shares", models.IntegerField(verbose_name="Shares")),
                (
                    "subscribers_gained",
                    models.IntegerField(verbose_name="Verlorene Abonnent*innen"),
                ),
                (
                    "subscribers_lost",
                    models.IntegerField(verbose_name="Gewonnene Abonnent*innen"),
                ),
                ("watch_time", models.DurationField(verbose_name="Sehdauer Gesamt")),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube_video",
                    models.ForeignKey(
                        help_text="ID des YouTube-Videos",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        related_query_name="analytics",
                        to="okr.youtubevideo",
                        verbose_name="YouTube-Video",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Video Analytics",
                "verbose_name_plural": "YouTube Video Analytics",
                "db_table": "youtube_video_analytics",
                "ordering": ["-date"],
                "unique_together": {("youtube_video", "date", "live_or_on_demand")},
            },
        ),
        migrations.CreateModel(
            name="YouTubeTrafficSource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("0: Direct or unknown", "Direct or unknown"),
                            ("1: YouTube advertising", "YouTube advertising"),
                            ("3: Browse features", "Browse features"),
                            ("4: YouTube channels", "YouTube channels"),
                            ("5: YouTube search", "YouTube search"),
                            ("7: Suggested videos", "Suggested videos"),
                            ("8: Other YouTube features", "Other YouTube features"),
                            ("9: External", "External"),
                            (
                                "11: Video cards and annotations",
                                "Video cards and annotations",
                            ),
                            ("14: Playlists", "Playlists"),
                            ("17: Notifications", "Notifications"),
                            ("18: Playlist pages", "Playlist pages"),
                            (
                                "19: Programming from claimed content",
                                "Programming from claimed content",
                            ),
                            (
                                "20: Interactive video endscreen",
                                "Interactive video endscreen",
                            ),
                            ("23: Stories", "Stories"),
                            ("24: Shorts", "Shorts"),
                            ("25: Product Pages", "Product Pages"),
                            ("26: Hashtag Pages", "Hashtag Pages"),
                            ("27: Sound Pages", "Sound Pages"),
                        ],
                        max_length=40,
                        verbose_name="Source Type",
                    ),
                ),
                ("views", models.IntegerField(null=True, verbose_name="Views")),
                (
                    "watch_time",
                    models.DurationField(null=True, verbose_name="Sehdauer Gesamt"),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="traffic_sources",
                        related_query_name="traffic_source",
                        to="okr.youtube",
                        verbose_name="YouTube-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Traffic Source",
                "verbose_name_plural": "YouTube Traffic Sources",
                "db_table": "youtube_traffic_source",
                "ordering": ["-date", "source_type"],
                "unique_together": {("youtube", "date", "source_type")},
            },
        ),
        migrations.CreateModel(
            name="YouTubeDemographics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                (
                    "age_range",
                    models.CharField(
                        choices=[
                            ("13-17", "13-17"),
                            ("18-24", "18-24"),
                            ("25-34", "25-34"),
                            ("35-44", "35-44"),
                            ("45-54", "45-54"),
                            ("55-64", "55-64"),
                            ("65+", "65+"),
                        ],
                        help_text="Die Altersgruppe, für die dieser Datenpunkt gilt",
                        max_length=20,
                        verbose_name="Altersgruppe",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Männlich"),
                            ("female", "Weiblich"),
                            ("other", "Andere Geschlechtsangabe"),
                        ],
                        help_text="Das Geschlecht, für das dieser Datenpunkt gilt",
                        max_length=20,
                        verbose_name="Geschlecht",
                    ),
                ),
                ("views", models.IntegerField(null=True, verbose_name="Views")),
                (
                    "watch_time",
                    models.DurationField(null=True, verbose_name="Sehdauer Gesamt"),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube",
                    models.ForeignKey(
                        help_text="Globale ID des YouTube-Accouts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demographics",
                        related_query_name="demographics",
                        to="okr.youtube",
                        verbose_name="YouTube-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube Demographics",
                "verbose_name_plural": "YouTube Demographics",
                "db_table": "youtube_demographics",
                "ordering": ["-date", "gender", "age_range"],
                "unique_together": {("youtube", "date", "age_range", "gender")},
            },
        ),
        migrations.CreateModel(
            name="YouTubeAnalytics",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Datum")),
                ("views", models.IntegerField(null=True, verbose_name="Views")),
                ("likes", models.IntegerField(null=True, verbose_name="Likes")),
                ("dislikes", models.IntegerField(null=True, verbose_name="Dislikes")),
                (
                    "subscribers",
                    models.IntegerField(
                        null=True, verbose_name="Abonnent*innen (Gesamt)"
                    ),
                ),
                (
                    "subscribers_gained",
                    models.IntegerField(
                        null=True, verbose_name="Hinzugewonnene Abonnent*innen"
                    ),
                ),
                (
                    "subscribers_lost",
                    models.IntegerField(
                        null=True, verbose_name="Verlorene Abonnent*innen"
                    ),
                ),
                (
                    "watch_time",
                    models.DurationField(null=True, verbose_name="Sehdauer Gesamt"),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "youtube",
                    models.ForeignKey(
                        help_text="Globale ID des YouTube-Accouts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        related_query_name="analytics",
                        to="okr.youtube",
                        verbose_name="YouTube-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "YouTube-Analytics",
                "verbose_name_plural": "YouTube-Analytics",
                "db_table": "youtube_analytics",
                "ordering": ["-date"],
                "unique_together": {("youtube", "date")},
            },
        ),
    ]
