# Generated by Django 3.2.7 on 2021-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0073_auto_20210914_1813"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubedemographics",
            name="views_percentage",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Anteil der Views",
            ),
        ),
        migrations.AlterField(
            model_name="youtubevideodemographics",
            name="views_percentage",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="Anteil der Views",
            ),
        ),
    ]
