# Generated by Django 3.2.7 on 2021-09-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "okr",
            "0073_youtubeanalytics_youtubedemographics_youtubetrafficsource_youtubevideo_youtubevideoanalytics_youtube",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="youtube",
            name="bigquery_suffix",
            field=models.TextField(
                default="wdraktuell",
                help_text="BigQuery Suffix, das im YouTube-Datentransfer in BigQuery konfiguriert wurde.",
                verbose_name="BigQuery Suffix",
            ),
            preserve_default=False,
        ),
    ]
