# Generated by Django 3.2.7 on 2021-09-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0074_youtube_bigquery_suffix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="youtubedemographics",
            name="views",
        ),
        migrations.RemoveField(
            model_name="youtubedemographics",
            name="watch_time",
        ),
        migrations.AddField(
            model_name="youtubedemographics",
            name="views_percentage",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=5,
                null=True,
                verbose_name="Anteil der Views",
            ),
        ),
    ]
