# Generated by Django 3.2.7 on 2021-10-20 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0075_auto_20211013_1636"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="youtubevideodemographics",
            options={
                "ordering": ["youtube_video", "gender", "age_range"],
                "verbose_name": "YouTube Video Demographics",
                "verbose_name_plural": "YouTube Video Demographics",
            },
        ),
        migrations.AlterUniqueTogether(
            name="youtubevideodemographics",
            unique_together={("youtube_video", "age_range", "gender")},
        ),
        migrations.RemoveField(
            model_name="youtubevideodemographics",
            name="date",
        ),
    ]
