# Generated by Django 3.2.7 on 2021-10-20 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0076_auto_20211020_1759"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstaComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "external_id",
                    models.TextField(
                        help_text="ID des Kommentars bei Instagram",
                        unique=True,
                        verbose_name="Externe ID",
                    ),
                ),
                (
                    "external_post_id",
                    models.TextField(
                        help_text="ID des dazugehörigen Posts bei Instagram",
                        verbose_name="Externe Post ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(verbose_name="Erstellungszeitpunkt"),
                ),
                (
                    "is_account_answer",
                    models.BooleanField(
                        help_text="True für Antwort des Accounts, False für User*innen-Kommentar",
                        verbose_name="Antwort des Accounts",
                    ),
                ),
                (
                    "username",
                    models.TextField(
                        help_text="Username der Kommentarverfasser*in",
                        verbose_name="Username",
                    ),
                ),
                (
                    "message_length",
                    models.IntegerField(
                        help_text="Zeichenzahl des Kommentars",
                        verbose_name="Kommentar-Länge",
                    ),
                ),
                (
                    "link",
                    models.TextField(
                        help_text="Link zum Kommentar bei Instagram",
                        verbose_name="Link",
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        help_text="Anzahl der Likes des Kommentars",
                        verbose_name="Likes",
                    ),
                ),
                (
                    "is_reply",
                    models.BooleanField(
                        help_text="True wenn Kommentar eine Antwort ist",
                        verbose_name="Ist Antwort",
                    ),
                ),
                (
                    "parent_comment_id",
                    models.TextField(
                        help_text="ID des Kommentars, auf den sich die Antwort bezieht",
                        null=True,
                        verbose_name="ID des Elternkommentars",
                    ),
                ),
                (
                    "is_hidden",
                    models.BooleanField(
                        help_text="True wenn Kommentar verborgen wurde",
                        verbose_name="Ist verborgen",
                    ),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "last_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Zuletzt upgedated"
                    ),
                ),
                (
                    "insta",
                    models.ForeignKey(
                        help_text="ID des Instagram-Accounts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        related_query_name="comment",
                        to="okr.insta",
                        verbose_name="Instagram-Account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram-Comment",
                "verbose_name_plural": "Instagram-Comments",
                "db_table": "instagram_comment",
                "ordering": ["-created_at"],
            },
        ),
    ]
