# Generated by Django 3.2.7 on 2021-11-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0077_instacomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubetrafficsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("advertising", "Werbung"),
                    ("annotation", "Annotation"),
                    ("campaign_card", "Kampagnenkarte"),
                    ("end_screen", "Endscreen"),
                    ("ext_url", "Externe URL"),
                    ("no_link_embedded", "Kein Link (eingebettet)"),
                    ("no_link_other", "Kein Link (sonstiges)"),
                    ("notification", "Benachrichtigung"),
                    ("playlist", "Playlist"),
                    ("promoted", "Promoted"),
                    ("related_video", "Related"),
                    ("shorts", "Shorts"),
                    ("subscriber", "Abonnent*in"),
                    ("yt_channel", "Youtube-Kanal"),
                    ("yt_other_page", "Sonstige Youtube-Seite"),
                    ("yt_playlist_page", "Youtube Playlist-Seite"),
                    ("yt_search", "Youtube-Suche"),
                    ("hashtags", "Hashtags"),
                ],
                max_length=40,
                verbose_name="Source Type",
            ),
        ),
    ]
