# Generated by Django 3.2.7 on 2021-11-23 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0078_alter_youtubetrafficsource_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstaVideoData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Datum des Datenpunkts", verbose_name="Datum"
                    ),
                ),
                (
                    "comments",
                    models.IntegerField(
                        help_text="Anzahl der Kommentare",
                        null=True,
                        verbose_name="Kommentare",
                    ),
                ),
                (
                    "likes",
                    models.IntegerField(
                        help_text="Anzahl der Likes", null=True, verbose_name="Likes"
                    ),
                ),
                ("reach", models.IntegerField(null=True, verbose_name="Reichweite")),
                (
                    "impressions",
                    models.IntegerField(null=True, verbose_name="Impressions"),
                ),
                (
                    "saved",
                    models.IntegerField(
                        help_text="Anzahl der Saves", null=True, verbose_name="Saves"
                    ),
                ),
                (
                    "video_views",
                    models.IntegerField(
                        help_text="Video-Views (3 sec oder mehr)",
                        null=True,
                        verbose_name="Video-Views",
                    ),
                ),
                (
                    "quintly_last_updated",
                    models.DateTimeField(
                        help_text="Zeitpunkt, zu dem Quintly die Daten zuletzt upgedated hat",
                        null=True,
                        verbose_name="Zuletzt upgedated (Quintly)",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Globale ID des Posts",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_data",
                        related_query_name="video_data",
                        to="okr.instapost",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Instagram Video-Daten",
                "verbose_name_plural": "Instagram Video-Daten",
                "db_table": "instagram_video_data",
                "ordering": ["-date"],
                "unique_together": {("post", "date")},
            },
        ),
    ]
