# Generated by Django 3.2.7 on 2021-11-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0079_instavideodata"),
    ]

    operations = [
        migrations.AddField(
            model_name="youtubevideoanalytics",
            name="clicks",
            field=models.IntegerField(null=True, verbose_name="Clicks"),
        ),
        migrations.AddField(
            model_name="youtubevideoanalytics",
            name="impressions",
            field=models.IntegerField(null=True, verbose_name="Impressions"),
        ),
        migrations.AlterField(
            model_name="youtubevideoanalytics",
            name="comments",
            field=models.IntegerField(null=True, verbose_name="Kommentare"),
        ),
        migrations.AlterField(
            model_name="youtubevideoanalytics",
            name="dislikes",
            field=models.IntegerField(null=True, verbose_name="Dislikes"),
        ),
        migrations.AlterField(
            model_name="youtubevideoanalytics",
            name="likes",
            field=models.IntegerField(null=True, verbose_name="Likes"),
        ),
        migrations.AlterField(
            model_name="youtubevideoanalytics",
            name="shares",
            field=models.IntegerField(null=True, verbose_name="Shares"),
        ),
        migrations.AlterField(
            model_name="youtubevideoanalytics",
            name="subscribers_gained",
            field=models.IntegerField(
                null=True, verbose_name="Verlorene Abonnent*innen"
            ),
        ),
        migrations.AlterField(
            model_name="youtubevideoanalytics",
            name="subscribers_lost",
            field=models.IntegerField(
                null=True, verbose_name="Gewonnene Abonnent*innen"
            ),
        ),
        migrations.AlterField(
            model_name="youtubevideoanalytics",
            name="views",
            field=models.IntegerField(null=True, verbose_name="Views"),
        ),
        migrations.AlterField(
            model_name="youtubevideoanalytics",
            name="watch_time",
            field=models.DurationField(null=True, verbose_name="Sehdauer Gesamt"),
        ),
    ]
