# Generated by Django 3.2.11 on 2022-02-28 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0080_auto_20211124_2207"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiktokpost",
            name="link",
            field=models.URLField(
                help_text="URL des Postings.", max_length=1024, verbose_name="Link"
            ),
        ),
        migrations.AlterField(
            model_name="tiktokpost",
            name="video_cover_url",
            field=models.URLField(
                help_text="URL des Video-Coverbildes.",
                max_length=1024,
                null=True,
                verbose_name="Video-Cover URL",
            ),
        ),
    ]
