# Generated by Django 3.2.11 on 2022-02-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("okr", "0081_auto_20220228_1347"),
    ]

    operations = [
        migrations.AddField(
            model_name="customkeyresultrecord",
            name="value_decimal",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Der Wert der Kennzahl als Kommazahl.",
                max_digits=20,
                null=True,
                verbose_name="Wert",
            ),
        ),
        migrations.AlterField(
            model_name="customkeyresult",
            name="key_result_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Ganzzahl"),
                    ("decimal", "Kommazahl"),
                ],
                help_text="Art der Kennzahl.",
                max_length=10,
                verbose_name="Kennzahlen-Typ",
            ),
        ),
        migrations.AlterField(
            model_name="customkeyresultrecord",
            name="value_integer",
            field=models.IntegerField(
                help_text="Der Wert der Kennzahl als Ganzzahl.",
                null=True,
                verbose_name="Wert",
            ),
        ),
    ]
