# Generated by Django 3.2.14 on 2022-08-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0082_auto_20220228_1403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="youtubevideodemographics",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "Männlich"),
                    ("female", "Weiblich"),
                    ("gender_other", "Andere Geschlechtsangabe"),
                    ("gender_unknown", "Geschlecht unbekannt"),
                ],
                help_text="Das Geschlecht, für das dieser Datenpunkt gilt",
                max_length=20,
                verbose_name="Geschlecht",
            ),
        ),
    ]
