# Generated by Django 5.0.7 on 2024-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("okr", "0088_alter_youtubetrafficsource_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instacomment",
            name="username",
            field=models.TextField(
                help_text="Username der Kommentarverfasser*in",
                null=True,
                verbose_name="Username",
            ),
        ),
    ]
